// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: achievements.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeAchievementReignsExcept = `-- name: CloseAchievementReignsExcept :execrows
UPDATE lifter_achievements
SET held_until = now()
WHERE achievement_slug = $1::text
  AND held_until IS NULL
  AND user_id <> ALL ($2::int[])
`

type CloseAchievementReignsExceptParams struct {
	AchievementSlug string  `json:"achievement_slug"`
	HolderIds       []int32 `json:"holder_ids"`
}

// CloseAchievementReignsExcept ends every open reign on one achievement that is
// not held by one of the lifters named.
//
// Expressed as "everybody except these" rather than "close this lifter's" because
// that is the shape of the fact the reconciler actually has: it knows who leads
// the board now, and it does not separately know who used to. One statement per
// board then handles every way a reign can end — dethroned by somebody else,
// overtaken into a tie that no longer includes them, or dropping off the board
// entirely because the metric stopped being defined for them.
//
// Passing an EMPTY array is meaningful and correct: it closes every open reign on
// that achievement, which is what should happen when a board has no entries at
// all. `<> ALL` on an empty array is true for every row, so this needs no special
// case in Go.
func (q *Queries) CloseAchievementReignsExcept(ctx context.Context, arg CloseAchievementReignsExceptParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeAchievementReignsExcept, arg.AchievementSlug, arg.HolderIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAchievementNotifications = `-- name: CreateAchievementNotifications :many

INSERT INTO notifications (user_id, actor_id, kind, achievement_slug)
SELECT u.id,
       $1::int,
       $2::text,
       $3::text
FROM users u
WHERE u.id = $1::int
   OR EXISTS (
     SELECT 1 FROM follows f
     WHERE f.followee_id = $1::int
       AND f.follower_id = u.id
   )
RETURNING user_id
`

type CreateAchievementNotificationsParams struct {
	ActorID         int32  `json:"actor_id"`
	Kind            string `json:"kind"`
	AchievementSlug string `json:"achievement_slug"`
}

// ---- notifications ----
// CreateAchievementNotifications tells the lifter who earned something, and
// anybody who follows them.
//
// Takes the KIND rather than writing one, which is the only thing that changed when
// levels became the second sort of achievement. A sibling query would have been a
// second copy of the audience rule below — the part actually worth getting right —
// kept in step by hand. Every word of the reasoning that follows applies to both
// kinds unchanged, which is itself the argument for one query.
//
// THIS USED TO GO TO THE WHOLE INSTALL AND NOT TO THE HOLDER, and the reversal is
// deliberate enough to record rather than quietly overwrite. The old comment argued
// that "a notification saying you did the thing you are looking at is noise", which
// was true while the crown reached everybody else and the holder had the ornament on
// their own name to learn from. It stopped being true the moment the panel became
// yours-and-the-people-you-chose: a lifter who follows nobody would have had a
// feature that never once spoke to them.
//
// So the rule is now the two audiences that have a reason to care. The holder,
// always — it is their achievement, and the row is what survives a missed toast and
// what opens the achievement dialog. And their followers, because following is the
// install's way of saying "tell me about this person".
//
// NOTE WHAT THIS BREAKS, in the table's own terms: notifications.actor_id is
// NOT NULL and 0026 wrote that every insert filters the actor out of the
// recipients, "because being told about your own applause is noise". That holds for
// applause and no longer holds here — these are the kinds whose recipient may be
// its own actor, and there are now two of them. The column is nullable-free and unconstrained, so nothing in the
// schema had to change, but a reader of 0026 should know one kind now disagrees
// with it.
//
// Everybody else on the install is told nothing. That is not a visibility rule —
// every crown stays on the leaderboard and beside every name, exactly as before —
// it is only about what gets pushed. See 0033.
//
// No session, no comment, no emoji. achievement_slug is the subject for both
// kinds, and it is what lets the panel name which board was won or which rung was
// reached.
// Returns everybody told, so the caller can wake their sockets.
func (q *Queries) CreateAchievementNotifications(ctx context.Context, arg CreateAchievementNotificationsParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, createAchievementNotifications, arg.ActorID, arg.Kind, arg.AchievementSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var user_id int32
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAchievements = `-- name: ListAchievements :many


SELECT slug,
       kind,
       metric,
       label,
       description,
       sort_order,
       level_threshold
FROM achievements
ORDER BY sort_order, slug
`

// Achievements: the catalogue, the ledger of reigns, and the reconciler's writes.
//
// The reads split by who is asking about whom, and the split is the whole point
// of the feature's shape. ListCurrentAchievementHolders is asked by every
// signed-in client about EVERYBODY, because a crown has to be drawable beside any
// name the app renders; ListLifterAchievements is asked about ONE lifter when
// their profile is open. The first is small and hot and answered by a partial
// index; the second is the only one that reads history.
//
// Nothing here is scoped to a caller, and that is deliberate rather than an
// omission. Achievements are public on the install by construction — the crown
// exists to be seen by other people, and the leaderboard it is derived from
// already lists every lifter to every signed-in account.
//
// The writes are the reconciler's, and they are a DIFF, not a rebuild. See
// refreshCrowns in internal/api/achievements.go for why: a reign is a continuous
// stretch, so the pass that runs hourly must leave an unchanged holder's row
// exactly as it found it.
// ---- reading ----
// ListAchievements is the catalogue: everything that can be earned.
//
// Ordered by sort_order so every surface lists them the way buildBoards orders
// the boards they come from, with volume last.
// The column list names every column of the table IN THE TABLE'S OWN ORDER, which
// is what makes sqlc reuse the Achievement model struct rather than emit a bespoke
// row type — the same trade the three RETURNING lists in sessions.sql make, and for
// the same reason. level_threshold is last here because 0035 added it last. Putting
// it beside `metric`, where it reads better, split this query off into its own type
// and broke every caller that passes the result to achievementToDTO.
func (q *Queries) ListAchievements(ctx context.Context) ([]Achievement, error) {
	rows, err := q.db.Query(ctx, listAchievements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Achievement
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(
			&i.Slug,
			&i.Kind,
			&i.Metric,
			&i.Label,
			&i.Description,
			&i.SortOrder,
			&i.LevelThreshold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentAchievementHolders = `-- name: ListCurrentAchievementHolders :many
SELECT la.achievement_slug,
       la.held_from,
       u.id AS user_id,
       u.username,
       u.display_name,
       u.avatar_color,
       COALESCE(ua.etag, '') AS avatar_etag
FROM lifter_achievements la
JOIN achievements a ON a.slug = la.achievement_slug
JOIN users u ON u.id = la.user_id
LEFT JOIN user_avatars ua ON ua.user_id = u.id
WHERE la.held_until IS NULL
ORDER BY a.sort_order, u.id
`

type ListCurrentAchievementHoldersRow struct {
	AchievementSlug string             `json:"achievement_slug"`
	HeldFrom        pgtype.Timestamptz `json:"held_from"`
	UserID          int32              `json:"user_id"`
	Username        string             `json:"username"`
	DisplayName     string             `json:"display_name"`
	AvatarColor     string             `json:"avatar_color"`
	AvatarEtag      string             `json:"avatar_etag"`
}

// ListCurrentAchievementHolders is who is wearing what, right now.
//
// THIS IS THE SITE-WIDE READ. Every signed-in client asks it and then draws from
// the answer beside every name on the feed, the roster, the leaderboard, the
// notification panel and the header. It has to be cheap, and it is: 0032's
// partial index holds only the open reigns, so this is bounded by the account
// count times the size of the catalogue rather than by the ledger's history.
//
// SEVERAL LIFTERS CAN HOLD ONE ACHIEVEMENT. The leaderboard gives tied figures
// the same rank, so two lifters genuinely level on a board are both first and
// both appear here under the same slug. A client must group these rather than
// assume one row per achievement.
//
// The lifter's own columns ride along for the reason ListNotificationGroups
// carries avatar_etag: the caller draws a person, and a lookup per holder would
// be a query per crown.
func (q *Queries) ListCurrentAchievementHolders(ctx context.Context) ([]ListCurrentAchievementHoldersRow, error) {
	rows, err := q.db.Query(ctx, listCurrentAchievementHolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentAchievementHoldersRow
	for rows.Next() {
		var i ListCurrentAchievementHoldersRow
		if err := rows.Scan(
			&i.AchievementSlug,
			&i.HeldFrom,
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarColor,
			&i.AvatarEtag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLifterAchievements = `-- name: ListLifterAchievements :many
SELECT a.slug,
       a.kind,
       a.metric,
       a.label,
       a.description,
       a.sort_order,
       a.level_threshold,
       COUNT(*)::bigint AS times_held,
       bool_or(la.held_until IS NULL) AS held_now,
       MIN(la.held_from)::timestamptz AS first_held_from,
       MAX(la.held_from)::timestamptz AS last_held_from
FROM lifter_achievements la
JOIN achievements a ON a.slug = la.achievement_slug
WHERE la.user_id = $1::int
GROUP BY a.slug, a.kind, a.metric, a.label, a.description, a.sort_order,
         a.level_threshold
ORDER BY held_now DESC, a.sort_order, a.slug
`

type ListLifterAchievementsRow struct {
	Slug           string             `json:"slug"`
	Kind           string             `json:"kind"`
	Metric         *string            `json:"metric"`
	Label          string             `json:"label"`
	Description    string             `json:"description"`
	SortOrder      int32              `json:"sort_order"`
	LevelThreshold *int32             `json:"level_threshold"`
	TimesHeld      int64              `json:"times_held"`
	HeldNow        bool               `json:"held_now"`
	FirstHeldFrom  pgtype.Timestamptz `json:"first_held_from"`
	LastHeldFrom   pgtype.Timestamptz `json:"last_held_from"`
}

// ListLifterAchievements is one lifter's profile section: what they hold now and
// what they have held before.
//
// FOLDED TO ONE ROW PER ACHIEVEMENT, with the reign count on it. That is what
// makes "held this three times" a number rather than a list the client has to
// count, and it keeps a lifter who has traded a crown back and forth for a year
// from returning a row per exchange.
//
// held_now leads the ordering because a crown someone is wearing is the thing
// they are being looked at for; past reigns sort behind it by the catalogue's own
// order rather than by recency, so the section reads the same way round every
// time it is opened.
//
// first_held_from and last_held_from are both returned because they answer
// different questions — "since when" for a current reign, "when last" for a
// lapsed one — and the client picks by held_now rather than asking twice.
func (q *Queries) ListLifterAchievements(ctx context.Context, userID int32) ([]ListLifterAchievementsRow, error) {
	rows, err := q.db.Query(ctx, listLifterAchievements, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLifterAchievementsRow
	for rows.Next() {
		var i ListLifterAchievementsRow
		if err := rows.Scan(
			&i.Slug,
			&i.Kind,
			&i.Metric,
			&i.Label,
			&i.Description,
			&i.SortOrder,
			&i.LevelThreshold,
			&i.TimesHeld,
			&i.HeldNow,
			&i.FirstHeldFrom,
			&i.LastHeldFrom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openAchievementReign = `-- name: OpenAchievementReign :execrows

INSERT INTO lifter_achievements (user_id, achievement_slug)
VALUES ($1::int, $2::text)
ON CONFLICT (achievement_slug, user_id) WHERE held_until IS NULL
DO NOTHING
`

type OpenAchievementReignParams struct {
	UserID          int32  `json:"user_id"`
	AchievementSlug string `json:"achievement_slug"`
}

// ---- the reconciler's two writes ----
//
// There is deliberately no "read the open reigns first" query to go with these.
// Between them they express the whole diff: the close says "everybody except
// these" and the open is an upsert, so neither needs a before-picture and a pass
// costs two statements per board rather than three.
// OpenAchievementReign starts a reign, or does nothing if one is already open.
//
// The ON CONFLICT is what makes the hourly pass idempotent, and it is what keeps
// a continuous reign as ONE row: a lifter who has been top all month already has
// an open reign, this does nothing, and their held_from still says when they took
// it rather than when the sweeper last ran.
//
// The conflict target repeats the index's WHERE clause because the index is
// partial — Postgres will not infer a partial index from the columns alone.
//
// :execrows so the caller learns whether this was a genuinely NEW reign. Only a
// new one is news, and only a new one raises notifications; without this the
// install would announce the same crown every hour, forever.
func (q *Queries) OpenAchievementReign(ctx context.Context, arg OpenAchievementReignParams) (int64, error) {
	result, err := q.db.Exec(ctx, openAchievementReign, arg.UserID, arg.AchievementSlug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
