// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assistance.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAssistance = `-- name: CreateAssistance :one
INSERT INTO program_day_assistance
    (user_id, program_day_id, exercise_id, position, sets, reps, weight_lb, rep_min, rep_max)
VALUES (
    $1::int,
    $2,
    $3,
    (SELECT COALESCE(MAX(position), 0) + 1
     FROM program_day_assistance
     WHERE user_id = $1::int
       AND program_day_id = $2),
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, program_day_id, exercise_id, position, sets, reps, weight_lb, rep_min, rep_max
`

type CreateAssistanceParams struct {
	UserID       int32          `json:"user_id"`
	ProgramDayID int32          `json:"program_day_id"`
	ExerciseID   int32          `json:"exercise_id"`
	Sets         int32          `json:"sets"`
	Reps         int32          `json:"reps"`
	WeightLb     pgtype.Numeric `json:"weight_lb"`
	RepMin       *int32         `json:"rep_min"`
	RepMax       *int32         `json:"rep_max"`
}

type CreateAssistanceRow struct {
	ID           int32          `json:"id"`
	ProgramDayID int32          `json:"program_day_id"`
	ExerciseID   int32          `json:"exercise_id"`
	Position     int32          `json:"position"`
	Sets         int32          `json:"sets"`
	Reps         int32          `json:"reps"`
	WeightLb     pgtype.Numeric `json:"weight_lb"`
	RepMin       *int32         `json:"rep_min"`
	RepMax       *int32         `json:"rep_max"`
}

// CreateAssistance appends to the end of the day's assistance block. position is
// computed in the INSERT rather than read and incremented by the handler: two
// concurrent adds that both read "3" would both write 4, and ordering by
// (position, id) would then be settled by insertion order anyway — but the
// subquery keeps the numbers honest for nothing extra.
func (q *Queries) CreateAssistance(ctx context.Context, arg CreateAssistanceParams) (CreateAssistanceRow, error) {
	row := q.db.QueryRow(ctx, createAssistance,
		arg.UserID,
		arg.ProgramDayID,
		arg.ExerciseID,
		arg.Sets,
		arg.Reps,
		arg.WeightLb,
		arg.RepMin,
		arg.RepMax,
	)
	var i CreateAssistanceRow
	err := row.Scan(
		&i.ID,
		&i.ProgramDayID,
		&i.ExerciseID,
		&i.Position,
		&i.Sets,
		&i.Reps,
		&i.WeightLb,
		&i.RepMin,
		&i.RepMax,
	)
	return i, err
}

const deleteAssistance = `-- name: DeleteAssistance :execrows
DELETE FROM program_day_assistance
WHERE id = $1
  AND user_id = $2::int
`

type DeleteAssistanceParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteAssistance(ctx context.Context, arg DeleteAssistanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAssistance, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAssistance = `-- name: GetAssistance :one
SELECT pda.id,
       pda.program_day_id,
       pda.exercise_id,
       e.name AS exercise_name,
       pda.position,
       pda.sets,
       pda.reps,
       pda.weight_lb,
       pda.rep_min,
       pda.rep_max,
       e.equipment
FROM program_day_assistance pda
JOIN exercises e ON e.id = pda.exercise_id
WHERE pda.id = $1
  AND pda.user_id = $2::int
`

type GetAssistanceParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

type GetAssistanceRow struct {
	ID           int32          `json:"id"`
	ProgramDayID int32          `json:"program_day_id"`
	ExerciseID   int32          `json:"exercise_id"`
	ExerciseName string         `json:"exercise_name"`
	Position     int32          `json:"position"`
	Sets         int32          `json:"sets"`
	Reps         int32          `json:"reps"`
	WeightLb     pgtype.Numeric `json:"weight_lb"`
	RepMin       *int32         `json:"rep_min"`
	RepMax       *int32         `json:"rep_max"`
	Equipment    string         `json:"equipment"`
}

func (q *Queries) GetAssistance(ctx context.Context, arg GetAssistanceParams) (GetAssistanceRow, error) {
	row := q.db.QueryRow(ctx, getAssistance, arg.ID, arg.UserID)
	var i GetAssistanceRow
	err := row.Scan(
		&i.ID,
		&i.ProgramDayID,
		&i.ExerciseID,
		&i.ExerciseName,
		&i.Position,
		&i.Sets,
		&i.Reps,
		&i.WeightLb,
		&i.RepMin,
		&i.RepMax,
		&i.Equipment,
	)
	return i, err
}

const lastAssistanceSets = `-- name: LastAssistanceSets :many
SELECT actual_reps, weight_lb, session_id
FROM (
    SELECT ss.actual_reps,
           ss.weight_lb,
           ss.set_number,
           s.id AS session_id,
           DENSE_RANK() OVER (ORDER BY s.performed_on DESC, s.id DESC) AS recency
    FROM session_sets ss
    JOIN sessions s ON s.id = ss.session_id
    WHERE ss.exercise_id = $1
      AND s.user_id = $2::int
      AND ss.actual_reps > 0
) ranked
WHERE recency = 1
ORDER BY set_number
`

type LastAssistanceSetsParams struct {
	ExerciseID int32 `json:"exercise_id"`
	UserID     int32 `json:"user_id"`
}

type LastAssistanceSetsRow struct {
	ActualReps *int32         `json:"actual_reps"`
	WeightLb   pgtype.Numeric `json:"weight_lb"`
	SessionID  int32          `json:"session_id"`
}

// LastAssistanceSets returns the reps actually logged on each set of a lift, the
// last time it was performed, with the weight worked.
//
// The double-progression engine needs per-set reps, which is what makes this its
// own query rather than an extension of ListExerciseHistory — that returns one
// row per session with the top weight and the best reps, a shape three other
// callers depend on and which cannot answer "did EVERY set reach the top of the
// range".
//
// actual_reps > 0 keeps unlogged sets out of the answer: a set nobody touched is
// not a set that fell short, and counting it would stop the range from ever
// topping out. Deliberately not scoped to a finished session, matching the
// carry-forward weight this sits beside — a lifter mid-workout is looking at
// what they just did.
//
// DENSE_RANK rather than a correlated subquery so the "which session was last"
// decision is made once, in the same pass that reads the rows.
//
// session_id rides along so the caller can tell whether 0022's weight pin has
// been spent. The pin records which session was last at the moment a lifter set
// the weight by hand; it outranks the carry-forward exactly while that is still
// the latest session, so the comparison needs the id this query already ranked
// by and would otherwise throw away.
func (q *Queries) LastAssistanceSets(ctx context.Context, arg LastAssistanceSetsParams) ([]LastAssistanceSetsRow, error) {
	rows, err := q.db.Query(ctx, lastAssistanceSets, arg.ExerciseID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LastAssistanceSetsRow
	for rows.Next() {
		var i LastAssistanceSetsRow
		if err := rows.Scan(&i.ActualReps, &i.WeightLb, &i.SessionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssistanceByDay = `-- name: ListAssistanceByDay :many

SELECT pda.id,
       pda.program_day_id,
       pda.exercise_id,
       e.name AS exercise_name,
       pda.position,
       pda.sets,
       pda.reps,
       pda.weight_lb,
       pda.weight_set_after_session_id,
       pda.rep_min,
       pda.rep_max,
       e.rest_seconds,
       e.equipment
FROM program_day_assistance pda
JOIN exercises e ON e.id = pda.exercise_id
WHERE pda.program_day_id = $1
  AND pda.user_id = $2::int
ORDER BY pda.position, pda.id
`

type ListAssistanceByDayParams struct {
	ProgramDayID int32 `json:"program_day_id"`
	UserID       int32 `json:"user_id"`
}

type ListAssistanceByDayRow struct {
	ID                      int32          `json:"id"`
	ProgramDayID            int32          `json:"program_day_id"`
	ExerciseID              int32          `json:"exercise_id"`
	ExerciseName            string         `json:"exercise_name"`
	Position                int32          `json:"position"`
	Sets                    int32          `json:"sets"`
	Reps                    int32          `json:"reps"`
	WeightLb                pgtype.Numeric `json:"weight_lb"`
	WeightSetAfterSessionID *int32         `json:"weight_set_after_session_id"`
	RepMin                  *int32         `json:"rep_min"`
	RepMax                  *int32         `json:"rep_max"`
	RestSeconds             int32          `json:"rest_seconds"`
	Equipment               string         `json:"equipment"`
}

// Assistance work: the exercises a lifter bolts onto the end of a program day.
//
// This table is the reason a SEEDED program never has to be edited. The seeded
// program_days and program_day_exercises are shared, and stay exactly as they
// were seeded; assistance is a per-user overlay keyed on (user_id,
// program_day_id). So the same Workout A is squat/bench/row for every account,
// the progression engine reads a prescription nobody has touched, and what one
// lifter adds is invisible to the next.
//
// Since 0029 a lifter can also build a program of their own, whose prescription
// they may edit directly. The overlay does not become redundant: it is still how
// you add work to a seeded program, still how you add work to somebody else's
// shared one, and still the only kind of addition that is private to you.
//
// Every query is scoped to one owner. That is not defence in depth here, it is
// the whole isolation model: program days are shared, so an unscoped read would
// hand one lifter another's plan on a row they are equally entitled to see.
//
// Deleting a row deletes a plan, never a performance. Sets already logged
// against the exercise stay in session_sets and keep counting toward volume and
// records — which is why ListSessionSets orders with a fallback for sets whose
// assistance row has since gone.
// ListAssistanceByDay returns one day's assistance in display order.
//
// rest_seconds rides along from the exercise so a prescribed session can carry a
// rest for assistance work too, without this table needing a column for it — the
// same reason 0011 put it on exercises in the first place. equipment comes with
// it and for the same reason: double progression moves the weight by the
// smallest jump the rack allows, and only the exercise knows whether that is a
// bar's 5 lb or a pair of bells' 10.
func (q *Queries) ListAssistanceByDay(ctx context.Context, arg ListAssistanceByDayParams) ([]ListAssistanceByDayRow, error) {
	rows, err := q.db.Query(ctx, listAssistanceByDay, arg.ProgramDayID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssistanceByDayRow
	for rows.Next() {
		var i ListAssistanceByDayRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramDayID,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.Position,
			&i.Sets,
			&i.Reps,
			&i.WeightLb,
			&i.WeightSetAfterSessionID,
			&i.RepMin,
			&i.RepMax,
			&i.RestSeconds,
			&i.Equipment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssistanceByProgram = `-- name: ListAssistanceByProgram :many
SELECT pda.id,
       pda.program_day_id,
       pda.exercise_id,
       e.name AS exercise_name,
       pda.position,
       pda.sets,
       pda.reps,
       pda.weight_lb,
       pda.rep_min,
       pda.rep_max,
       e.equipment
FROM program_day_assistance pda
JOIN exercises e ON e.id = pda.exercise_id
JOIN program_days pd ON pd.id = pda.program_day_id
WHERE pd.program_id = $1
  AND pd.archived_at IS NULL
  AND pda.user_id = $2::int
ORDER BY pd.position, pda.position, pda.id
`

type ListAssistanceByProgramParams struct {
	ProgramID int32 `json:"program_id"`
	UserID    int32 `json:"user_id"`
}

type ListAssistanceByProgramRow struct {
	ID           int32          `json:"id"`
	ProgramDayID int32          `json:"program_day_id"`
	ExerciseID   int32          `json:"exercise_id"`
	ExerciseName string         `json:"exercise_name"`
	Position     int32          `json:"position"`
	Sets         int32          `json:"sets"`
	Reps         int32          `json:"reps"`
	WeightLb     pgtype.Numeric `json:"weight_lb"`
	RepMin       *int32         `json:"rep_min"`
	RepMax       *int32         `json:"rep_max"`
	Equipment    string         `json:"equipment"`
}

// ListAssistanceByProgram returns every day's assistance across one program, so
// the program detail response can be assembled in one round trip. Ordered by day
// then position, mirroring ListPrescriptionsByProgram.
//
// equipment rides along for the same reason it does on the by-day query, but for
// the client rather than the engine: the program page lets a lifter edit a
// prescription, and the number input's step and the copy promising "+N lb next
// time" both have to name the jump this movement can actually make.
func (q *Queries) ListAssistanceByProgram(ctx context.Context, arg ListAssistanceByProgramParams) ([]ListAssistanceByProgramRow, error) {
	rows, err := q.db.Query(ctx, listAssistanceByProgram, arg.ProgramID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssistanceByProgramRow
	for rows.Next() {
		var i ListAssistanceByProgramRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramDayID,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.Position,
			&i.Sets,
			&i.Reps,
			&i.WeightLb,
			&i.RepMin,
			&i.RepMax,
			&i.Equipment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssistance = `-- name: UpdateAssistance :one
UPDATE program_day_assistance pda
SET sets      = $1,
    reps      = $2,
    weight_lb = $3,
    rep_min   = $4,
    rep_max   = $5,
    weight_set_after_session_id = CASE
        WHEN NOT $6::boolean
            THEN pda.weight_set_after_session_id
        ELSE COALESCE((
            SELECT s.id
            FROM session_sets ss
            JOIN sessions s ON s.id = ss.session_id
            WHERE ss.exercise_id = pda.exercise_id
              AND s.user_id = pda.user_id
              AND ss.actual_reps > 0
            ORDER BY s.performed_on DESC, s.id DESC
            LIMIT 1
        ), 0)
    END
WHERE pda.id = $7
  AND pda.user_id = $8::int
RETURNING id, program_day_id, exercise_id, position, sets, reps, weight_lb, rep_min, rep_max
`

type UpdateAssistanceParams struct {
	Sets      int32          `json:"sets"`
	Reps      int32          `json:"reps"`
	WeightLb  pgtype.Numeric `json:"weight_lb"`
	RepMin    *int32         `json:"rep_min"`
	RepMax    *int32         `json:"rep_max"`
	PinWeight bool           `json:"pin_weight"`
	ID        int32          `json:"id"`
	UserID    int32          `json:"user_id"`
}

type UpdateAssistanceRow struct {
	ID           int32          `json:"id"`
	ProgramDayID int32          `json:"program_day_id"`
	ExerciseID   int32          `json:"exercise_id"`
	Position     int32          `json:"position"`
	Sets         int32          `json:"sets"`
	Reps         int32          `json:"reps"`
	WeightLb     pgtype.Numeric `json:"weight_lb"`
	RepMin       *int32         `json:"rep_min"`
	RepMax       *int32         `json:"rep_max"`
}

// UpdateAssistance writes every mutable column; the handler merges the PATCH
// body with current values first, the same shape as UpdateSessionSet. The owner
// check is repeated here rather than inferred from the preceding GetAssistance,
// for the reason given there.
//
// rep_min and rep_max are narg rather than arg because NULL is meaningful: it is
// how a lifter turns the rep range back off and returns the lift to carrying its
// weight forward. A COALESCE here would make that unsayable.
//
// Naming a weight arms the pin 0022 added, which is what makes the edit outrank
// the carry-forward until the lift is next performed.
//
// The trigger is the field being PRESENT in the patch, decided by the handler
// and passed in, rather than the new weight differing from the stored one.
// Comparing against the stored weight looks equivalent and is not: the stored
// weight is what the lift was ADDED at, while the number the lifter is looking
// at is the prescribed one the carry-forward has since moved. A curl added at
// 30 that has climbed to 50 is stored as 30, so "set it to 30" compares equal
// and would arm nothing — which is precisely the bug this column exists to fix,
// surviving inside its own fix. Presence is the only signal that means "a
// lifter typed this", and PATCH already carries it.
//
// The subquery is the same "which session was this lift last done in" that
// LastAssistanceSets ranks by, down to the actual_reps > 0 filter — a set
// nobody touched is not a session the lift was performed in, and the two have
// to agree or a pin could be armed against a session the prescription does not
// consider the latest. COALESCE to 0 for a lift never logged, so "no session
// yet" is a value that can match rather than a NULL that never does.
func (q *Queries) UpdateAssistance(ctx context.Context, arg UpdateAssistanceParams) (UpdateAssistanceRow, error) {
	row := q.db.QueryRow(ctx, updateAssistance,
		arg.Sets,
		arg.Reps,
		arg.WeightLb,
		arg.RepMin,
		arg.RepMax,
		arg.PinWeight,
		arg.ID,
		arg.UserID,
	)
	var i UpdateAssistanceRow
	err := row.Scan(
		&i.ID,
		&i.ProgramDayID,
		&i.ExerciseID,
		&i.Position,
		&i.Sets,
		&i.Reps,
		&i.WeightLb,
		&i.RepMin,
		&i.RepMax,
	)
	return i, err
}
