// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assistance.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAssistance = `-- name: CreateAssistance :one
INSERT INTO program_day_assistance
    (user_id, program_day_id, exercise_id, position, sets, reps, weight_lb)
VALUES (
    $1::int,
    $2,
    $3,
    (SELECT COALESCE(MAX(position), 0) + 1
     FROM program_day_assistance
     WHERE user_id = $1::int
       AND program_day_id = $2),
    $4,
    $5,
    $6
)
RETURNING id, program_day_id, exercise_id, position, sets, reps, weight_lb
`

type CreateAssistanceParams struct {
	UserID       int32          `json:"user_id"`
	ProgramDayID int32          `json:"program_day_id"`
	ExerciseID   int32          `json:"exercise_id"`
	Sets         int32          `json:"sets"`
	Reps         int32          `json:"reps"`
	WeightLb     pgtype.Numeric `json:"weight_lb"`
}

type CreateAssistanceRow struct {
	ID           int32          `json:"id"`
	ProgramDayID int32          `json:"program_day_id"`
	ExerciseID   int32          `json:"exercise_id"`
	Position     int32          `json:"position"`
	Sets         int32          `json:"sets"`
	Reps         int32          `json:"reps"`
	WeightLb     pgtype.Numeric `json:"weight_lb"`
}

// CreateAssistance appends to the end of the day's assistance block. position is
// computed in the INSERT rather than read and incremented by the handler: two
// concurrent adds that both read "3" would both write 4, and ordering by
// (position, id) would then be settled by insertion order anyway — but the
// subquery keeps the numbers honest for nothing extra.
func (q *Queries) CreateAssistance(ctx context.Context, arg CreateAssistanceParams) (CreateAssistanceRow, error) {
	row := q.db.QueryRow(ctx, createAssistance,
		arg.UserID,
		arg.ProgramDayID,
		arg.ExerciseID,
		arg.Sets,
		arg.Reps,
		arg.WeightLb,
	)
	var i CreateAssistanceRow
	err := row.Scan(
		&i.ID,
		&i.ProgramDayID,
		&i.ExerciseID,
		&i.Position,
		&i.Sets,
		&i.Reps,
		&i.WeightLb,
	)
	return i, err
}

const deleteAssistance = `-- name: DeleteAssistance :execrows
DELETE FROM program_day_assistance
WHERE id = $1
  AND user_id = $2::int
`

type DeleteAssistanceParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteAssistance(ctx context.Context, arg DeleteAssistanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAssistance, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAssistance = `-- name: GetAssistance :one
SELECT pda.id,
       pda.program_day_id,
       pda.exercise_id,
       e.name AS exercise_name,
       pda.position,
       pda.sets,
       pda.reps,
       pda.weight_lb
FROM program_day_assistance pda
JOIN exercises e ON e.id = pda.exercise_id
WHERE pda.id = $1
  AND pda.user_id = $2::int
`

type GetAssistanceParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

type GetAssistanceRow struct {
	ID           int32          `json:"id"`
	ProgramDayID int32          `json:"program_day_id"`
	ExerciseID   int32          `json:"exercise_id"`
	ExerciseName string         `json:"exercise_name"`
	Position     int32          `json:"position"`
	Sets         int32          `json:"sets"`
	Reps         int32          `json:"reps"`
	WeightLb     pgtype.Numeric `json:"weight_lb"`
}

func (q *Queries) GetAssistance(ctx context.Context, arg GetAssistanceParams) (GetAssistanceRow, error) {
	row := q.db.QueryRow(ctx, getAssistance, arg.ID, arg.UserID)
	var i GetAssistanceRow
	err := row.Scan(
		&i.ID,
		&i.ProgramDayID,
		&i.ExerciseID,
		&i.ExerciseName,
		&i.Position,
		&i.Sets,
		&i.Reps,
		&i.WeightLb,
	)
	return i, err
}

const listAssistanceByDay = `-- name: ListAssistanceByDay :many

SELECT pda.id,
       pda.program_day_id,
       pda.exercise_id,
       e.name AS exercise_name,
       pda.position,
       pda.sets,
       pda.reps,
       pda.weight_lb
FROM program_day_assistance pda
JOIN exercises e ON e.id = pda.exercise_id
WHERE pda.program_day_id = $1
  AND pda.user_id = $2::int
ORDER BY pda.position, pda.id
`

type ListAssistanceByDayParams struct {
	ProgramDayID int32 `json:"program_day_id"`
	UserID       int32 `json:"user_id"`
}

type ListAssistanceByDayRow struct {
	ID           int32          `json:"id"`
	ProgramDayID int32          `json:"program_day_id"`
	ExerciseID   int32          `json:"exercise_id"`
	ExerciseName string         `json:"exercise_name"`
	Position     int32          `json:"position"`
	Sets         int32          `json:"sets"`
	Reps         int32          `json:"reps"`
	WeightLb     pgtype.Numeric `json:"weight_lb"`
}

// Assistance work: the exercises a lifter bolts onto the end of a program day.
//
// This table is the reason programs never have to be edited. program_days and
// program_day_exercises are shared and seeded, and stay that way; assistance is
// a per-user overlay keyed on (user_id, program_day_id). So the same Workout A
// is squat/bench/row for every account, the progression engine reads a
// prescription nobody has touched, and what one lifter adds is invisible to the
// next.
//
// Every query is scoped to one owner. That is not defence in depth here, it is
// the whole isolation model: program days are shared, so an unscoped read would
// hand one lifter another's plan on a row they are equally entitled to see.
//
// Deleting a row deletes a plan, never a performance. Sets already logged
// against the exercise stay in session_sets and keep counting toward volume and
// records — which is why ListSessionSets orders with a fallback for sets whose
// assistance row has since gone.
// ListAssistanceByDay returns one day's assistance in display order.
func (q *Queries) ListAssistanceByDay(ctx context.Context, arg ListAssistanceByDayParams) ([]ListAssistanceByDayRow, error) {
	rows, err := q.db.Query(ctx, listAssistanceByDay, arg.ProgramDayID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssistanceByDayRow
	for rows.Next() {
		var i ListAssistanceByDayRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramDayID,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.Position,
			&i.Sets,
			&i.Reps,
			&i.WeightLb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssistanceByProgram = `-- name: ListAssistanceByProgram :many
SELECT pda.id,
       pda.program_day_id,
       pda.exercise_id,
       e.name AS exercise_name,
       pda.position,
       pda.sets,
       pda.reps,
       pda.weight_lb
FROM program_day_assistance pda
JOIN exercises e ON e.id = pda.exercise_id
JOIN program_days pd ON pd.id = pda.program_day_id
WHERE pd.program_id = $1
  AND pda.user_id = $2::int
ORDER BY pd.position, pda.position, pda.id
`

type ListAssistanceByProgramParams struct {
	ProgramID int32 `json:"program_id"`
	UserID    int32 `json:"user_id"`
}

type ListAssistanceByProgramRow struct {
	ID           int32          `json:"id"`
	ProgramDayID int32          `json:"program_day_id"`
	ExerciseID   int32          `json:"exercise_id"`
	ExerciseName string         `json:"exercise_name"`
	Position     int32          `json:"position"`
	Sets         int32          `json:"sets"`
	Reps         int32          `json:"reps"`
	WeightLb     pgtype.Numeric `json:"weight_lb"`
}

// ListAssistanceByProgram returns every day's assistance across one program, so
// the program detail response can be assembled in one round trip. Ordered by day
// then position, mirroring ListPrescriptionsByProgram.
func (q *Queries) ListAssistanceByProgram(ctx context.Context, arg ListAssistanceByProgramParams) ([]ListAssistanceByProgramRow, error) {
	rows, err := q.db.Query(ctx, listAssistanceByProgram, arg.ProgramID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssistanceByProgramRow
	for rows.Next() {
		var i ListAssistanceByProgramRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramDayID,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.Position,
			&i.Sets,
			&i.Reps,
			&i.WeightLb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssistance = `-- name: UpdateAssistance :one
UPDATE program_day_assistance
SET sets      = $1,
    reps      = $2,
    weight_lb = $3
WHERE id = $4
  AND user_id = $5::int
RETURNING id, program_day_id, exercise_id, position, sets, reps, weight_lb
`

type UpdateAssistanceParams struct {
	Sets     int32          `json:"sets"`
	Reps     int32          `json:"reps"`
	WeightLb pgtype.Numeric `json:"weight_lb"`
	ID       int32          `json:"id"`
	UserID   int32          `json:"user_id"`
}

type UpdateAssistanceRow struct {
	ID           int32          `json:"id"`
	ProgramDayID int32          `json:"program_day_id"`
	ExerciseID   int32          `json:"exercise_id"`
	Position     int32          `json:"position"`
	Sets         int32          `json:"sets"`
	Reps         int32          `json:"reps"`
	WeightLb     pgtype.Numeric `json:"weight_lb"`
}

// UpdateAssistance writes all three mutable columns; the handler merges the
// PATCH body with current values first, the same shape as UpdateSessionSet. The
// owner check is repeated here rather than inferred from the preceding
// GetAssistance, for the reason given there.
func (q *Queries) UpdateAssistance(ctx context.Context, arg UpdateAssistanceParams) (UpdateAssistanceRow, error) {
	row := q.db.QueryRow(ctx, updateAssistance,
		arg.Sets,
		arg.Reps,
		arg.WeightLb,
		arg.ID,
		arg.UserID,
	)
	var i UpdateAssistanceRow
	err := row.Scan(
		&i.ID,
		&i.ProgramDayID,
		&i.ExerciseID,
		&i.Position,
		&i.Sets,
		&i.Reps,
		&i.WeightLb,
	)
	return i, err
}
