// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercises.sql

package store

import (
	"context"
)

const getExercise = `-- name: GetExercise :one
SELECT id, name
FROM exercises
WHERE id = $1
`

type GetExerciseRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetExercise(ctx context.Context, id int32) (GetExerciseRow, error) {
	row := q.db.QueryRow(ctx, getExercise, id)
	var i GetExerciseRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listExercises = `-- name: ListExercises :many
SELECT id, name
FROM exercises
ORDER BY name
`

type ListExercisesRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) ListExercises(ctx context.Context) ([]ListExercisesRow, error) {
	rows, err := q.db.Query(ctx, listExercises)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExercisesRow
	for rows.Next() {
		var i ListExercisesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
