// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercises.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getExercise = `-- name: GetExercise :one
SELECT id, name
FROM exercises
WHERE id = $1
`

type GetExerciseRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetExercise(ctx context.Context, id int32) (GetExerciseRow, error) {
	row := q.db.QueryRow(ctx, getExercise, id)
	var i GetExerciseRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listExerciseHistory = `-- name: ListExerciseHistory :many
SELECT s.performed_on,
       MAX(ss.weight_lb)::numeric               AS weight_lb,
       COALESCE(MAX(ss.actual_reps), 0)::int        AS reps,
       COALESCE(BOOL_AND(ss.completed), false)::bool AS completed
FROM session_sets ss
JOIN sessions s ON s.id = ss.session_id
WHERE ss.exercise_id = $1
  AND s.user_id = $2::int
  AND ss.actual_reps > 0
GROUP BY s.id, s.performed_on
ORDER BY s.performed_on, s.id
`

type ListExerciseHistoryParams struct {
	ExerciseID int32 `json:"exercise_id"`
	UserID     int32 `json:"user_id"`
}

type ListExerciseHistoryRow struct {
	PerformedOn pgtype.Date    `json:"performed_on"`
	WeightLb    pgtype.Numeric `json:"weight_lb"`
	Reps        int32          `json:"reps"`
	Completed   bool           `json:"completed"`
}

// ListExerciseHistory returns one point per performed session for a lift
// (oldest first): the top weight worked, the best reps, and whether every set
// hit target. Only logged sessions (a set with actual_reps > 0) are included.
func (q *Queries) ListExerciseHistory(ctx context.Context, arg ListExerciseHistoryParams) ([]ListExerciseHistoryRow, error) {
	rows, err := q.db.Query(ctx, listExerciseHistory, arg.ExerciseID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExerciseHistoryRow
	for rows.Next() {
		var i ListExerciseHistoryRow
		if err := rows.Scan(
			&i.PerformedOn,
			&i.WeightLb,
			&i.Reps,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExercises = `-- name: ListExercises :many
SELECT id, name
FROM exercises
ORDER BY name
`

type ListExercisesRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) ListExercises(ctx context.Context) ([]ListExercisesRow, error) {
	rows, err := q.db.Query(ctx, listExercises)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExercisesRow
	for rows.Next() {
		var i ListExercisesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
