// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: follows.sql

package store

import (
	"context"
)

const followLifter = `-- name: FollowLifter :execrows

INSERT INTO follows (followee_id, follower_id)
VALUES ($1::int, $2::int)
ON CONFLICT (followee_id, follower_id) DO NOTHING
`

type FollowLifterParams struct {
	FolloweeID int32 `json:"followee_id"`
	FollowerID int32 `json:"follower_id"`
}

// Following, which decides whose achievements reach whose panel.
//
// Two writes and no reads. That is not an omission: nothing asks this table a
// question on its own. The roster and the profile test it with a correlated EXISTS
// in users.sql, and the crown fan-out joins it in achievements.sql — both of which
// keep the follow check next to the row it qualifies rather than making a caller
// fetch a set and filter in Go.
//
// Both writes are modelled on AddSessionReaction and RemoveSessionReaction in
// recognition.sql, down to the reasoning: a button that toggles a state should
// report the state, not complain about the number of times it was pressed.
// FollowLifter records that one lifter wants to hear about another.
//
// ON CONFLICT DO NOTHING rather than an error, for AddSessionReaction's reason: the
// primary key makes a repeat press a no-op, which is what pressing Follow twice
// means. Returning a 409 would be reporting a mistake nobody made, and checking
// first would be a race under concurrent presses that the constraint settles for
// free.
//
// :execrows so a caller CAN tell a new follow from a repeat, even though the
// handler answers 204 either way. Nothing needs the distinction today — unlike
// applause, a follow raises no notification — and the row count is there because
// the day it does, the alternative is a read-then-write race.
//
// Following yourself cannot be written: 0033's CHECK refuses it, and the handler
// refuses it first with a message worth reading.
func (q *Queries) FollowLifter(ctx context.Context, arg FollowLifterParams) (int64, error) {
	result, err := q.db.Exec(ctx, followLifter, arg.FolloweeID, arg.FollowerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unfollowLifter = `-- name: UnfollowLifter :execrows
DELETE FROM follows
WHERE followee_id = $1::int
  AND follower_id = $2::int
`

type UnfollowLifterParams struct {
	FolloweeID int32 `json:"followee_id"`
	FollowerID int32 `json:"follower_id"`
}

// UnfollowLifter stops it.
//
// :execrows to match its sibling, and the handler discards the count for
// RemoveSessionReaction's reason: the caller asked for a state — "I do not follow
// this lifter" — and that state holds whether or not a row went. Reporting 404 for
// a follow already gone would turn a double-tap into an error.
func (q *Queries) UnfollowLifter(ctx context.Context, arg UnfollowLifterParams) (int64, error) {
	result, err := q.db.Exec(ctx, unfollowLifter, arg.FolloweeID, arg.FollowerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
