// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gym.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPlate = `-- name: AddPlate :exec
INSERT INTO user_plates (user_id, plate_lb, pairs)
VALUES ($1::int, $2, $3)
ON CONFLICT (user_id, plate_lb) DO UPDATE
SET pairs = EXCLUDED.pairs
`

type AddPlateParams struct {
	UserID  int32          `json:"user_id"`
	PlateLb pgtype.Numeric `json:"plate_lb"`
	Pairs   int32          `json:"pairs"`
}

func (q *Queries) AddPlate(ctx context.Context, arg AddPlateParams) error {
	_, err := q.db.Exec(ctx, addPlate, arg.UserID, arg.PlateLb, arg.Pairs)
	return err
}

const deleteAllPlates = `-- name: DeleteAllPlates :exec
DELETE FROM user_plates WHERE user_id = $1::int
`

// DeleteAllPlates and AddPlate are the two halves of a replace. The API writes
// the inventory whole rather than patching a denomination at a time: the client
// edits a rack, not a row, and a partial write would leave a plate the lifter
// deleted still loadable.
func (q *Queries) DeleteAllPlates(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteAllPlates, userID)
	return err
}

const deleteBaseline = `-- name: DeleteBaseline :execrows
DELETE FROM user_lift_baselines
WHERE user_id = $1::int
  AND exercise_id = $2
`

type DeleteBaselineParams struct {
	UserID     int32 `json:"user_id"`
	ExerciseID int32 `json:"exercise_id"`
}

func (q *Queries) DeleteBaseline(ctx context.Context, arg DeleteBaselineParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBaseline, arg.UserID, arg.ExerciseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBarWeight = `-- name: GetBarWeight :one

SELECT COALESCE(g.bar_weight_lb, 45.0)::numeric AS bar_weight_lb
FROM users u
LEFT JOIN user_gym g ON g.user_id = u.id
WHERE u.id = $1::int
`

// GetBarWeight returns the lifter's bar, falling back to the column default for
// an account that has never opened the setup screen. COALESCE over a LEFT JOIN
// rather than a plain SELECT so a missing row answers the question instead of
// returning no rows — the caller wants a bar weight, and "45" is always a
// truthful answer to that even when nothing has been configured.
func (q *Queries) GetBarWeight(ctx context.Context, userID int32) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getBarWeight, userID)
	var bar_weight_lb pgtype.Numeric
	err := row.Scan(&bar_weight_lb)
	return bar_weight_lb, err
}

const listBaselines = `-- name: ListBaselines :many
SELECT exercise_id, weight_lb
FROM user_lift_baselines
WHERE user_id = $1::int
`

type ListBaselinesRow struct {
	ExerciseID int32          `json:"exercise_id"`
	WeightLb   pgtype.Numeric `json:"weight_lb"`
}

// ListBaselines returns every starting weight the lifter has overridden. Read
// whole rather than one lift at a time because prescribe() needs the day's worth
// at once and a program day is a handful of lifts.
func (q *Queries) ListBaselines(ctx context.Context, userID int32) ([]ListBaselinesRow, error) {
	rows, err := q.db.Query(ctx, listBaselines, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBaselinesRow
	for rows.Next() {
		var i ListBaselinesRow
		if err := rows.Scan(&i.ExerciseID, &i.WeightLb); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlates = `-- name: ListPlates :many
SELECT plate_lb, pairs
FROM user_plates
WHERE user_id = $1::int
ORDER BY plate_lb DESC
`

type ListPlatesRow struct {
	PlateLb pgtype.Numeric `json:"plate_lb"`
	Pairs   int32          `json:"pairs"`
}

// ListPlates returns the lifter's inventory, heaviest first — the order the
// greedy loader wants and the order a rack is read in.
func (q *Queries) ListPlates(ctx context.Context, userID int32) ([]ListPlatesRow, error) {
	rows, err := q.db.Query(ctx, listPlates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlatesRow
	for rows.Next() {
		var i ListPlatesRow
		if err := rows.Scan(&i.PlateLb, &i.Pairs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedDefaultPlates = `-- name: SeedDefaultPlates :exec
INSERT INTO user_plates (user_id, plate_lb, pairs)
SELECT $1::int, v.plate_lb, v.pairs
FROM (VALUES
    (45.0, 2),
    (35.0, 2),
    (25.0, 2),
    (10.0, 2),
    ( 5.0, 2),
    ( 2.5, 2)
) AS v(plate_lb, pairs)
ON CONFLICT DO NOTHING
`

// SeedDefaultPlates gives a new account the standard set, matching what
// 0013_gym_setup wrote for the accounts that already existed. Called from
// register() inside the same transaction, so an account either has an inventory
// or does not exist — which is what lets an empty inventory mean "owns no
// plates" rather than "never configured".
func (q *Queries) SeedDefaultPlates(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, seedDefaultPlates, userID)
	return err
}

const setBarWeight = `-- name: SetBarWeight :exec
INSERT INTO user_gym (user_id, bar_weight_lb)
VALUES ($1::int, $2)
ON CONFLICT (user_id) DO UPDATE
SET bar_weight_lb = EXCLUDED.bar_weight_lb,
    updated_at    = now()
`

type SetBarWeightParams struct {
	UserID      int32          `json:"user_id"`
	BarWeightLb pgtype.Numeric `json:"bar_weight_lb"`
}

// SetBarWeight creates the row or updates it. An upsert rather than an
// INSERT-then-UPDATE because the row's absence is the normal state, not an
// error: see 0013.
func (q *Queries) SetBarWeight(ctx context.Context, arg SetBarWeightParams) error {
	_, err := q.db.Exec(ctx, setBarWeight, arg.UserID, arg.BarWeightLb)
	return err
}

const setBaseline = `-- name: SetBaseline :exec
INSERT INTO user_lift_baselines (user_id, exercise_id, weight_lb)
VALUES ($1::int, $2, $3)
ON CONFLICT (user_id, exercise_id) DO UPDATE
SET weight_lb = EXCLUDED.weight_lb
`

type SetBaselineParams struct {
	UserID     int32          `json:"user_id"`
	ExerciseID int32          `json:"exercise_id"`
	WeightLb   pgtype.Numeric `json:"weight_lb"`
}

// SetBaseline records where a lift starts for this lifter. Upsert for the same
// reason SetBarWeight is one.
//
// The exercise_id FK is what scopes this: a baseline for an exercise that does
// not exist, or for someone else's custom movement, fails on the constraint
// rather than needing a handler check — exercises.created_by_user_id is already
// the visibility rule, and the API checks it before calling this so the failure
// is a 404 rather than a 500.
func (q *Queries) SetBaseline(ctx context.Context, arg SetBaselineParams) error {
	_, err := q.db.Exec(ctx, setBaseline, arg.UserID, arg.ExerciseID, arg.WeightLb)
	return err
}
