// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: houses.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addHouseMember = `-- name: AddHouseMember :execrows
INSERT INTO house_members (user_id, house_id, is_owner)
VALUES ($1::int,
        $2::int,
        $3::boolean)
ON CONFLICT (user_id) DO NOTHING
`

type AddHouseMemberParams struct {
	UserID  int32 `json:"user_id"`
	HouseID int32 `json:"house_id"`
	IsOwner bool  `json:"is_owner"`
}

// AddHouseMember joins a lifter to a House.
//
// ON CONFLICT DO NOTHING rather than an upsert that moves them: a lifter who is
// already in a House has to leave it first, and quietly relocating them would
// turn the approval of a stale request into a silent transfer out of the House
// they actually chose. :execrows so the caller can tell the difference — zero
// means they were already somewhere, and that is a 409.
func (q *Queries) AddHouseMember(ctx context.Context, arg AddHouseMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, addHouseMember, arg.UserID, arg.HouseID, arg.IsOwner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createHouse = `-- name: CreateHouse :one

INSERT INTO houses (name, sigil, tagline, description, icon, icon_color)
VALUES ($1::text,
        $2::text,
        $3::text,
        $4::text,
        $5::text,
        $6::text)
RETURNING id, name, sigil, tagline, description, icon, icon_color, created_at
`

type CreateHouseParams struct {
	Name        string `json:"name"`
	Sigil       string `json:"sigil"`
	Tagline     string `json:"tagline"`
	Description string `json:"description"`
	Icon        string `json:"icon"`
	IconColor   string `json:"icon_color"`
}

// ---- writing ----
func (q *Queries) CreateHouse(ctx context.Context, arg CreateHouseParams) (House, error) {
	row := q.db.QueryRow(ctx, createHouse,
		arg.Name,
		arg.Sigil,
		arg.Tagline,
		arg.Description,
		arg.Icon,
		arg.IconColor,
	)
	var i House
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sigil,
		&i.Tagline,
		&i.Description,
		&i.Icon,
		&i.IconColor,
		&i.CreatedAt,
	)
	return i, err
}

const createHouseNotification = `-- name: CreateHouseNotification :many

INSERT INTO notifications (user_id, actor_id, kind, house_id)
SELECT $1::int,
       $2::int,
       $3::text,
       $4::int
WHERE $1::int <> $2::int
RETURNING user_id
`

type CreateHouseNotificationParams struct {
	UserID  int32  `json:"user_id"`
	ActorID int32  `json:"actor_id"`
	Kind    string `json:"kind"`
	HouseID int32  `json:"house_id"`
}

// ---- notifications ----
// CreateHouseNotification tells one lifter about one House event.
//
// One statement for all three kinds, because they differ only in who is told and
// what the sentence says. The WHERE is the rule 0026 set and every fan-out in
// this repo keeps: the actor is never a recipient, so a request tells the owner
// and not the requester, and a decision tells the requester and not the owner.
//
// :many returning user_id rather than :exec, matching the other fan-outs, so the
// handler knows whose socket to wake without asking a second time.
func (q *Queries) CreateHouseNotification(ctx context.Context, arg CreateHouseNotificationParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, createHouseNotification,
		arg.UserID,
		arg.ActorID,
		arg.Kind,
		arg.HouseID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var user_id int32
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createJoinRequest = `-- name: CreateJoinRequest :one
INSERT INTO house_join_requests (house_id, user_id)
VALUES ($1::int, $2::int)
RETURNING id, house_id, user_id, requested_at
`

type CreateJoinRequestParams struct {
	HouseID int32 `json:"house_id"`
	UserID  int32 `json:"user_id"`
}

type CreateJoinRequestRow struct {
	ID          int32              `json:"id"`
	HouseID     int32              `json:"house_id"`
	UserID      int32              `json:"user_id"`
	RequestedAt pgtype.Timestamptz `json:"requested_at"`
}

func (q *Queries) CreateJoinRequest(ctx context.Context, arg CreateJoinRequestParams) (CreateJoinRequestRow, error) {
	row := q.db.QueryRow(ctx, createJoinRequest, arg.HouseID, arg.UserID)
	var i CreateJoinRequestRow
	err := row.Scan(
		&i.ID,
		&i.HouseID,
		&i.UserID,
		&i.RequestedAt,
	)
	return i, err
}

const decideJoinRequest = `-- name: DecideJoinRequest :execrows
UPDATE house_join_requests
SET decided_at = now(),
    decided_by = $1::int,
    outcome    = $2::text
WHERE id = $3::int
  AND decided_at IS NULL
`

type DecideJoinRequestParams struct {
	DecidedBy *int32 `json:"decided_by"`
	Outcome   string `json:"outcome"`
	ID        int32  `json:"id"`
}

// DecideJoinRequest closes one request.
//
// The decided_at IS NULL guard is what makes deciding idempotent under a double
// tap: the second call updates nothing and :execrows reports zero, rather than
// overwriting an approval with a decline because two taps raced.
func (q *Queries) DecideJoinRequest(ctx context.Context, arg DecideJoinRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideJoinRequest, arg.DecidedBy, arg.Outcome, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getHouse = `-- name: GetHouse :one
SELECT h.id,
       h.name,
       h.sigil,
       h.tagline,
       h.description,
       h.icon,
       h.icon_color,
       h.created_at
FROM houses h
WHERE h.id = $1::int
`

// GetHouse is one House in full, for its page.
func (q *Queries) GetHouse(ctx context.Context, id int32) (House, error) {
	row := q.db.QueryRow(ctx, getHouse, id)
	var i House
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sigil,
		&i.Tagline,
		&i.Description,
		&i.Icon,
		&i.IconColor,
		&i.CreatedAt,
	)
	return i, err
}

const getHouseMembership = `-- name: GetHouseMembership :one
SELECT hm.user_id,
       hm.house_id,
       hm.is_owner,
       hm.joined_at
FROM house_members hm
WHERE hm.user_id = $1::int
`

// GetHouseMembership is the caller's own membership, or no row.
//
// One row at most, because user_id is the primary key of house_members. That is
// "one House at a time" being read back rather than being enforced.
func (q *Queries) GetHouseMembership(ctx context.Context, userID int32) (HouseMember, error) {
	row := q.db.QueryRow(ctx, getHouseMembership, userID)
	var i HouseMember
	err := row.Scan(
		&i.UserID,
		&i.HouseID,
		&i.IsOwner,
		&i.JoinedAt,
	)
	return i, err
}

const getHouseOwner = `-- name: GetHouseOwner :one
SELECT hm.user_id,
       hm.is_owner
FROM house_members hm
WHERE hm.house_id = $1::int
ORDER BY hm.is_owner DESC, hm.joined_at, hm.user_id
LIMIT 1
`

type GetHouseOwnerRow struct {
	UserID  int32 `json:"user_id"`
	IsOwner bool  `json:"is_owner"`
}

// GetHouseOwner is the effective owner, and it is the whole of that rule in one
// statement.
//
// is_owner DESC puts the marked owner first when there is one. When there is not
// — an owner deleted their account and the cascade took the membership row with
// it before any transfer could run — the ordering falls through to the
// longest-standing member, which is the same lifter a transfer would have
// chosen. So an ownerless House answers this question rather than needing to be
// repaired first, and there is no scheduled pass looking for one.
//
// Returns NO ROW when the House has no members at all. That is a real state and
// not an impossible one: the leave path lets an empty House stand rather than
// deleting it. Callers read the empty answer as "unowned" — owner-only
// endpoints 404, and the asking endpoint hands the House to whoever asked.
func (q *Queries) GetHouseOwner(ctx context.Context, houseID int32) (GetHouseOwnerRow, error) {
	row := q.db.QueryRow(ctx, getHouseOwner, houseID)
	var i GetHouseOwnerRow
	err := row.Scan(&i.UserID, &i.IsOwner)
	return i, err
}

const getJoinRequest = `-- name: GetJoinRequest :one
SELECT r.id,
       r.house_id,
       r.user_id,
       r.requested_at,
       r.decided_at,
       r.outcome
FROM house_join_requests r
WHERE r.id = $1::int
`

type GetJoinRequestRow struct {
	ID          int32              `json:"id"`
	HouseID     int32              `json:"house_id"`
	UserID      int32              `json:"user_id"`
	RequestedAt pgtype.Timestamptz `json:"requested_at"`
	DecidedAt   pgtype.Timestamptz `json:"decided_at"`
	Outcome     *string            `json:"outcome"`
}

// GetJoinRequest is one request by id, for the handlers that decide it.
func (q *Queries) GetJoinRequest(ctx context.Context, id int32) (GetJoinRequestRow, error) {
	row := q.db.QueryRow(ctx, getJoinRequest, id)
	var i GetJoinRequestRow
	err := row.Scan(
		&i.ID,
		&i.HouseID,
		&i.UserID,
		&i.RequestedAt,
		&i.DecidedAt,
		&i.Outcome,
	)
	return i, err
}

const getOpenRequest = `-- name: GetOpenRequest :one
SELECT r.id,
       r.requested_at
FROM house_join_requests r
WHERE r.house_id = $1::int
  AND r.user_id = $2::int
  AND r.decided_at IS NULL
`

type GetOpenRequestParams struct {
	HouseID int32 `json:"house_id"`
	UserID  int32 `json:"user_id"`
}

type GetOpenRequestRow struct {
	ID          int32              `json:"id"`
	RequestedAt pgtype.Timestamptz `json:"requested_at"`
}

// GetOpenRequest is the caller's own pending request to one House, or no row.
//
// What the detail page's button reads: no row means "Request to join", a row
// means "Requested" and offers to withdraw it.
func (q *Queries) GetOpenRequest(ctx context.Context, arg GetOpenRequestParams) (GetOpenRequestRow, error) {
	row := q.db.QueryRow(ctx, getOpenRequest, arg.HouseID, arg.UserID)
	var i GetOpenRequestRow
	err := row.Scan(&i.ID, &i.RequestedAt)
	return i, err
}

const listHouseMembers = `-- name: ListHouseMembers :many
SELECT u.id,
       u.username,
       u.display_name,
       u.avatar_color,
       COALESCE(ua.etag, '') AS avatar_etag,
       (
         SELECT MAX(s.performed_on)
         FROM sessions s
         WHERE s.user_id = u.id
           AND EXISTS (
             SELECT 1 FROM session_sets ss
             WHERE ss.session_id = s.id AND ss.actual_reps > 0
           )
       )::date AS last_trained_on,
       hm.is_owner,
       hm.joined_at
FROM house_members hm
JOIN users u ON u.id = hm.user_id
LEFT JOIN user_avatars ua ON ua.user_id = u.id
WHERE hm.house_id = $1::int
ORDER BY hm.is_owner DESC, hm.joined_at, u.id
`

type ListHouseMembersRow struct {
	ID            int32              `json:"id"`
	Username      string             `json:"username"`
	DisplayName   string             `json:"display_name"`
	AvatarColor   string             `json:"avatar_color"`
	AvatarEtag    string             `json:"avatar_etag"`
	LastTrainedOn pgtype.Date        `json:"last_trained_on"`
	IsOwner       bool               `json:"is_owner"`
	JoinedAt      pgtype.Timestamptz `json:"joined_at"`
}

// ListHouseMembers is a House's members as lifters, for its page.
//
// The same lifter columns ListLifters returns, and deliberately no more: this is
// a social surface, and the note at the top of db/queries/users.sql explains why
// the administrative columns stay out of one. last_trained_on rides along
// because the member list shows it, the same way the roster does.
func (q *Queries) ListHouseMembers(ctx context.Context, houseID int32) ([]ListHouseMembersRow, error) {
	rows, err := q.db.Query(ctx, listHouseMembers, houseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHouseMembersRow
	for rows.Next() {
		var i ListHouseMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarColor,
			&i.AvatarEtag,
			&i.LastTrainedOn,
			&i.IsOwner,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouseMemberships = `-- name: ListHouseMemberships :many
SELECT hm.user_id,
       hm.house_id,
       hm.is_owner
FROM house_members hm
ORDER BY hm.house_id, hm.joined_at, hm.user_id
`

type ListHouseMembershipsRow struct {
	UserID  int32 `json:"user_id"`
	HouseID int32 `json:"house_id"`
	IsOwner bool  `json:"is_owner"`
}

// ListHouseMemberships is who is in what, for the whole install.
//
// The other half of the site-wide read, and the one that actually answers "which
// sigil goes beside this name". Returned flat rather than folded into ListHouses
// as an array, because the client keys it into a map by lifter id and a flat list
// is what that wants — see sigilFor in src/ui/src/lib/houses.svelte.ts.
func (q *Queries) ListHouseMemberships(ctx context.Context) ([]ListHouseMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listHouseMemberships)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHouseMembershipsRow
	for rows.Next() {
		var i ListHouseMembershipsRow
		if err := rows.Scan(&i.UserID, &i.HouseID, &i.IsOwner); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHouses = `-- name: ListHouses :many


SELECT h.id,
       h.name,
       h.sigil,
       h.tagline,
       h.icon,
       h.icon_color,
       h.created_at,
       (
         SELECT COUNT(*)
         FROM house_members hm
         WHERE hm.house_id = h.id
       )::int AS member_count
FROM houses h
ORDER BY lower(h.name), h.id
`

type ListHousesRow struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Sigil       string             `json:"sigil"`
	Tagline     string             `json:"tagline"`
	Icon        string             `json:"icon"`
	IconColor   string             `json:"icon_color"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	MemberCount int32              `json:"member_count"`
}

// Houses: the group, its members, and the requests to join one.
//
// The reads split the way achievements.sql splits, and for the same reason.
// ListHouses and ListHouseMemberships are asked by every signed-in client about
// EVERY House, because a sigil has to be drawable beside any name the app
// renders. Everything below them is asked about ONE House when its page is open.
// The first pair is small and hot; the rest are the detail page's.
//
// Nothing here is scoped to a caller. That is deliberate and it is the feature's
// central decision: a House groups, it does not gate. internal/api/lifters.go
// explains why this install has no per-lifter visibility filter, and adding one
// here would have reversed that premise rather than extended it. Which House a
// lifter is in is exactly as public as the name it is drawn beside.
//
// The writes are ordinary except for three rules the SQL cannot state on its
// own, all of which live in internal/api/houses.go: the first approval of a
// lifter's several requests supersedes the rest; the last member leaving hands
// ownership to the longest-standing of whoever is left; and a House with nobody
// left in it STANDS rather than being deleted, to be claimed outright by the
// next lifter who asks.
// ---- reading ----
// ListHouses is the site-wide read: every House, without its description.
//
// description is left out on purpose. It is the only unbounded column here, it
// is read on exactly one screen, and this is the payload every client fetches on
// load in order to draw sigils. GetHouse below is where the long version lives.
//
// member_count rides along because the list screen shows it and the alternative
// is a second round trip per row.
func (q *Queries) ListHouses(ctx context.Context) ([]ListHousesRow, error) {
	rows, err := q.db.Query(ctx, listHouses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHousesRow
	for rows.Next() {
		var i ListHousesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sigil,
			&i.Tagline,
			&i.Icon,
			&i.IconColor,
			&i.CreatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingHouseRequests = `-- name: ListPendingHouseRequests :many
SELECT r.id,
       r.requested_at,
       u.id AS user_id,
       u.username,
       u.display_name,
       u.avatar_color,
       COALESCE(ua.etag, '') AS avatar_etag
FROM house_join_requests r
JOIN users u ON u.id = r.user_id
LEFT JOIN user_avatars ua ON ua.user_id = u.id
WHERE r.house_id = $1::int
  AND r.decided_at IS NULL
ORDER BY r.requested_at DESC, r.id DESC
`

type ListPendingHouseRequestsRow struct {
	ID          int32              `json:"id"`
	RequestedAt pgtype.Timestamptz `json:"requested_at"`
	UserID      int32              `json:"user_id"`
	Username    string             `json:"username"`
	DisplayName string             `json:"display_name"`
	AvatarColor string             `json:"avatar_color"`
	AvatarEtag  string             `json:"avatar_etag"`
}

// ListPendingHouseRequests is what an owner is shown, newest first.
//
// Only the owner ever reads this — the handler checks before asking — which is
// why the requester's name is joined in here rather than being fetched per row
// by a client that would not be allowed to see the list anyway.
func (q *Queries) ListPendingHouseRequests(ctx context.Context, houseID int32) ([]ListPendingHouseRequestsRow, error) {
	rows, err := q.db.Query(ctx, listPendingHouseRequests, houseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingHouseRequestsRow
	for rows.Next() {
		var i ListPendingHouseRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestedAt,
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarColor,
			&i.AvatarEtag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockHouse = `-- name: LockHouse :one
SELECT id
FROM houses
WHERE id = $1::int
FOR UPDATE
`

// LockHouse holds the House's row for the rest of the transaction.
//
// Asking to join decides between two outcomes on one read — claim an EMPTY
// House, or file a request against an occupied one — and that read has to be
// stable or both can happen at once. Under read committed, two lifters asking
// the same empty House in the same instant would each see no owner and each walk
// in as owner: AddHouseMember's ON CONFLICT is on user_id, which says "one House
// per LIFTER" and has nothing to say about two lifters joining one House.
//
// So that decision is made under this lock. The second lifter waits, re-reads a
// House that now has an owner, and files an ordinary request instead.
func (q *Queries) LockHouse(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, lockHouse, id)
	var id_2 int32
	err := row.Scan(&id_2)
	return id_2, err
}

const promoteLongestStandingMember = `-- name: PromoteLongestStandingMember :execrows
UPDATE house_members
SET is_owner = true
WHERE user_id = (
    SELECT hm.user_id
    FROM house_members hm
    WHERE hm.house_id = $1::int
    ORDER BY hm.joined_at, hm.user_id
    LIMIT 1
)
`

// PromoteLongestStandingMember hands a House to whoever has been in it longest.
//
// Run after the owner's membership row is already gone, so the ordering here
// cannot pick them again. Ties broken by user_id for the reason the leaderboard
// breaks them that way: two rows written in the same transaction have the same
// timestamp, and an arbitrary-but-stable answer beats a different one per call.
func (q *Queries) PromoteLongestStandingMember(ctx context.Context, houseID int32) (int64, error) {
	result, err := q.db.Exec(ctx, promoteLongestStandingMember, houseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeHouseMember = `-- name: RemoveHouseMember :execrows
DELETE FROM house_members
WHERE user_id = $1::int
`

func (q *Queries) RemoveHouseMember(ctx context.Context, userID int32) (int64, error) {
	result, err := q.db.Exec(ctx, removeHouseMember, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supersedeHouseOpenRequests = `-- name: SupersedeHouseOpenRequests :execrows
UPDATE house_join_requests
SET decided_at = now(),
    outcome    = 'superseded'
WHERE house_id = $1::int
  AND decided_at IS NULL
`

// SupersedeHouseOpenRequests closes every request still open against one House.
//
// Called in the same transaction as the last member leaving it. Back when that
// deleted the House, these rows went with it through the cascade; now the House
// stands, and without this they would sit open forever against a House with no
// owner to answer them.
//
// Leaving them would also lock the askers OUT of the very House they asked for:
// an empty House is claimed by asking, `viewer.openRequestId` makes the page
// offer Withdraw instead of Request to join, and so the one lifter who already
// wanted in would be the one who could not take it.
func (q *Queries) SupersedeHouseOpenRequests(ctx context.Context, houseID int32) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeHouseOpenRequests, houseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supersedeOtherOpenRequests = `-- name: SupersedeOtherOpenRequests :execrows
UPDATE house_join_requests
SET decided_at = now(),
    outcome    = 'superseded'
WHERE user_id = $1::int
  AND id <> $2::int
  AND decided_at IS NULL
`

type SupersedeOtherOpenRequestsParams struct {
	UserID   int32 `json:"user_id"`
	ExceptID int32 `json:"except_id"`
}

// SupersedeOtherOpenRequests closes every OTHER request a lifter has open.
//
// Called in the same transaction as the approval that made them unanswerable. A
// lifter may ask several Houses at once, which is the friendly behaviour; what
// would not be friendly is leaving those requests sitting in other owners'
// queues, where approving one would fail against a lifter who now has a House.
func (q *Queries) SupersedeOtherOpenRequests(ctx context.Context, arg SupersedeOtherOpenRequestsParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeOtherOpenRequests, arg.UserID, arg.ExceptID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateHouse = `-- name: UpdateHouse :one
UPDATE houses
SET name        = $1::text,
    sigil       = $2::text,
    tagline     = $3::text,
    description = $4::text,
    icon        = $5::text,
    icon_color  = $6::text
WHERE id = $7::int
RETURNING id, name, sigil, tagline, description, icon, icon_color, created_at
`

type UpdateHouseParams struct {
	Name        string `json:"name"`
	Sigil       string `json:"sigil"`
	Tagline     string `json:"tagline"`
	Description string `json:"description"`
	Icon        string `json:"icon"`
	IconColor   string `json:"icon_color"`
	ID          int32  `json:"id"`
}

// UpdateHouse rewrites the identity half of a House. Owner only, checked in the
// handler — there is no caller column here to check it against.
func (q *Queries) UpdateHouse(ctx context.Context, arg UpdateHouseParams) (House, error) {
	row := q.db.QueryRow(ctx, updateHouse,
		arg.Name,
		arg.Sigil,
		arg.Tagline,
		arg.Description,
		arg.Icon,
		arg.IconColor,
		arg.ID,
	)
	var i House
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sigil,
		&i.Tagline,
		&i.Description,
		&i.Icon,
		&i.IconColor,
		&i.CreatedAt,
	)
	return i, err
}
