// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Exercise struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Program struct {
	ID              int32              `json:"id"`
	Name            string             `json:"name"`
	Description     string             `json:"description"`
	ProgressionKind string             `json:"progression_kind"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ProgramDay struct {
	ID        int32  `json:"id"`
	ProgramID int32  `json:"program_id"`
	Name      string `json:"name"`
	Position  int32  `json:"position"`
	Weekday   *int32 `json:"weekday"`
}

type ProgramDayExercise struct {
	ID               int32          `json:"id"`
	ProgramDayID     int32          `json:"program_day_id"`
	ExerciseID       int32          `json:"exercise_id"`
	Position         int32          `json:"position"`
	Sets             int32          `json:"sets"`
	Reps             int32          `json:"reps"`
	StartingWeightLb pgtype.Numeric `json:"starting_weight_lb"`
}

type Session struct {
	ID           int32              `json:"id"`
	ProgramDayID int32              `json:"program_day_id"`
	PerformedOn  pgtype.Date        `json:"performed_on"`
	Notes        string             `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type SessionSet struct {
	ID         int32          `json:"id"`
	SessionID  int32          `json:"session_id"`
	ExerciseID int32          `json:"exercise_id"`
	SetNumber  int32          `json:"set_number"`
	TargetReps int32          `json:"target_reps"`
	ActualReps *int32         `json:"actual_reps"`
	WeightLb   pgtype.Numeric `json:"weight_lb"`
	Completed  bool           `json:"completed"`
}
