// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Achievement struct {
	Slug        string  `json:"slug"`
	Kind        string  `json:"kind"`
	Metric      *string `json:"metric"`
	Label       string  `json:"label"`
	Description string  `json:"description"`
	SortOrder   int32   `json:"sort_order"`
}

type Exercise struct {
	ID              int32              `json:"id"`
	Name            string             `json:"name"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	MuscleGroup     string             `json:"muscle_group"`
	Equipment       string             `json:"equipment"`
	IsAccessory     bool               `json:"is_accessory"`
	CreatedByUserID *int32             `json:"created_by_user_id"`
	RestSeconds     int32              `json:"rest_seconds"`
}

type Follow struct {
	FolloweeID int32              `json:"followee_id"`
	FollowerID int32              `json:"follower_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type GeneratedActivityRun struct {
	Day         pgtype.Date        `json:"day"`
	Sessions    int32              `json:"sessions"`
	Reactions   int32              `json:"reactions"`
	Comments    int32              `json:"comments"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
}

type GeneratedActivitySchedule struct {
	ID        int32              `json:"id"`
	Enabled   bool               `json:"enabled"`
	Lifters   int32              `json:"lifters"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type LifterAchievement struct {
	ID              int32              `json:"id"`
	UserID          int32              `json:"user_id"`
	AchievementSlug string             `json:"achievement_slug"`
	HeldFrom        pgtype.Timestamptz `json:"held_from"`
	HeldUntil       pgtype.Timestamptz `json:"held_until"`
}

type Notification struct {
	ID              int32              `json:"id"`
	UserID          int32              `json:"user_id"`
	ActorID         int32              `json:"actor_id"`
	Kind            string             `json:"kind"`
	SessionID       *int32             `json:"session_id"`
	CommentID       *int32             `json:"comment_id"`
	Emoji           *string            `json:"emoji"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ReadAt          pgtype.Timestamptz `json:"read_at"`
	ArchivedAt      pgtype.Timestamptz `json:"archived_at"`
	AchievementSlug *string            `json:"achievement_slug"`
}

type Program struct {
	ID              int32              `json:"id"`
	Name            string             `json:"name"`
	Description     string             `json:"description"`
	ProgressionKind string             `json:"progression_kind"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CreatedByUserID *int32             `json:"created_by_user_id"`
	IsShared        bool               `json:"is_shared"`
	ArchivedAt      pgtype.Timestamptz `json:"archived_at"`
}

type ProgramDay struct {
	ID         int32              `json:"id"`
	ProgramID  int32              `json:"program_id"`
	Name       string             `json:"name"`
	Position   int32              `json:"position"`
	Weekday    *int32             `json:"weekday"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

type ProgramDayAssistance struct {
	ID                      int32              `json:"id"`
	UserID                  int32              `json:"user_id"`
	ProgramDayID            int32              `json:"program_day_id"`
	ExerciseID              int32              `json:"exercise_id"`
	Position                int32              `json:"position"`
	Sets                    int32              `json:"sets"`
	Reps                    int32              `json:"reps"`
	WeightLb                pgtype.Numeric     `json:"weight_lb"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	RepMin                  *int32             `json:"rep_min"`
	RepMax                  *int32             `json:"rep_max"`
	WeightSetAfterSessionID *int32             `json:"weight_set_after_session_id"`
}

type ProgramDayExercise struct {
	ID               int32          `json:"id"`
	ProgramDayID     int32          `json:"program_day_id"`
	ExerciseID       int32          `json:"exercise_id"`
	Position         int32          `json:"position"`
	Sets             int32          `json:"sets"`
	Reps             int32          `json:"reps"`
	StartingWeightLb pgtype.Numeric `json:"starting_weight_lb"`
}

type ProgramDayExerciseSet struct {
	ProgramDayExerciseID int32          `json:"program_day_exercise_id"`
	SetNumber            int32          `json:"set_number"`
	Reps                 int32          `json:"reps"`
	PctOfTop             pgtype.Numeric `json:"pct_of_top"`
}

type ReportRun struct {
	ID          int32              `json:"id"`
	UserID      int32              `json:"user_id"`
	PeriodKind  string             `json:"period_kind"`
	PeriodStart pgtype.Date        `json:"period_start"`
	Status      string             `json:"status"`
	Attempts    int32              `json:"attempts"`
	ClaimedAt   pgtype.Timestamptz `json:"claimed_at"`
	SentAt      pgtype.Timestamptz `json:"sent_at"`
	LastError   string             `json:"last_error"`
}

type Session struct {
	ID           int32              `json:"id"`
	ProgramDayID int32              `json:"program_day_id"`
	PerformedOn  pgtype.Date        `json:"performed_on"`
	Notes        string             `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	UserID       *int32             `json:"user_id"`
	BodyweightLb pgtype.Numeric     `json:"bodyweight_lb"`
}

type SessionComment struct {
	ID        int32              `json:"id"`
	SessionID int32              `json:"session_id"`
	UserID    int32              `json:"user_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SessionReaction struct {
	SessionID int32              `json:"session_id"`
	UserID    int32              `json:"user_id"`
	Emoji     string             `json:"emoji"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SessionSet struct {
	ID         int32          `json:"id"`
	SessionID  int32          `json:"session_id"`
	ExerciseID int32          `json:"exercise_id"`
	SetNumber  int32          `json:"set_number"`
	TargetReps int32          `json:"target_reps"`
	ActualReps *int32         `json:"actual_reps"`
	WeightLb   pgtype.Numeric `json:"weight_lb"`
	Completed  bool           `json:"completed"`
	IsBonus    bool           `json:"is_bonus"`
}

type User struct {
	ID                 int32              `json:"id"`
	Username           string             `json:"username"`
	DisplayName        string             `json:"display_name"`
	AvatarColor        string             `json:"avatar_color"`
	PasswordHash       string             `json:"password_hash"`
	IsAdmin            bool               `json:"is_admin"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CurrentProgramID   *int32             `json:"current_program_id"`
	MustChangePassword bool               `json:"must_change_password"`
}

type UserAvatar struct {
	UserID    int32              `json:"user_id"`
	Mime      string             `json:"mime"`
	Bytes     []byte             `json:"bytes"`
	Etag      string             `json:"etag"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserGym struct {
	UserID               int32              `json:"user_id"`
	BarWeightLb          pgtype.Numeric     `json:"bar_weight_lb"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DumbbellStepLb       pgtype.Numeric     `json:"dumbbell_step_lb"`
	MachineStepLb        pgtype.Numeric     `json:"machine_step_lb"`
	CableStepLb          pgtype.Numeric     `json:"cable_step_lb"`
	BandStepLb           pgtype.Numeric     `json:"band_step_lb"`
	EquipmentConfirmedAt pgtype.Timestamptz `json:"equipment_confirmed_at"`
}

type UserLiftBaseline struct {
	UserID     int32          `json:"user_id"`
	ExerciseID int32          `json:"exercise_id"`
	WeightLb   pgtype.Numeric `json:"weight_lb"`
}

type UserPlate struct {
	UserID  int32          `json:"user_id"`
	PlateLb pgtype.Numeric `json:"plate_lb"`
	Pairs   int32          `json:"pairs"`
}

type UserSession struct {
	TokenHash  []byte             `json:"token_hash"`
	UserID     int32              `json:"user_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastSeen   pgtype.Timestamptz `json:"last_seen"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	Persistent bool               `json:"persistent"`
}
