// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: programs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProgram = `-- name: GetProgram :one
SELECT id, name, description, progression_kind
FROM programs
WHERE id = $1
`

type GetProgramRow struct {
	ID              int32  `json:"id"`
	Name            string `json:"name"`
	Description     string `json:"description"`
	ProgressionKind string `json:"progression_kind"`
}

func (q *Queries) GetProgram(ctx context.Context, id int32) (GetProgramRow, error) {
	row := q.db.QueryRow(ctx, getProgram, id)
	var i GetProgramRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ProgressionKind,
	)
	return i, err
}

const getProgramDay = `-- name: GetProgramDay :one
SELECT id, program_id, name, position
FROM program_days
WHERE id = $1
`

func (q *Queries) GetProgramDay(ctx context.Context, id int32) (ProgramDay, error) {
	row := q.db.QueryRow(ctx, getProgramDay, id)
	var i ProgramDay
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.Name,
		&i.Position,
	)
	return i, err
}

const listLiftHistory = `-- name: ListLiftHistory :many
SELECT s.performed_on,
       MAX(ss.weight_lb)::numeric  AS weight_lb,
       BOOL_AND(ss.completed)      AS success
FROM sessions s
JOIN session_sets ss ON ss.session_id = s.id
JOIN program_days pd ON pd.id = s.program_day_id
WHERE pd.program_id = $1
  AND ss.exercise_id = $2
GROUP BY s.id, s.performed_on
ORDER BY s.performed_on, s.id
`

type ListLiftHistoryParams struct {
	ProgramID  int32 `json:"program_id"`
	ExerciseID int32 `json:"exercise_id"`
}

type ListLiftHistoryRow struct {
	PerformedOn pgtype.Date    `json:"performed_on"`
	WeightLb    pgtype.Numeric `json:"weight_lb"`
	Success     bool           `json:"success"`
}

// ListLiftHistory returns one row per past session in which a lift was
// performed within a program, oldest first, for the progression engine.
// Scope is the whole program (all days) because a lift such as the squat
// progresses continuously across Workout A and B. A session "succeeds" for the
// lift only if every logged set for it was completed; weight_lb is the top
// weight worked that session.
func (q *Queries) ListLiftHistory(ctx context.Context, arg ListLiftHistoryParams) ([]ListLiftHistoryRow, error) {
	rows, err := q.db.Query(ctx, listLiftHistory, arg.ProgramID, arg.ExerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiftHistoryRow
	for rows.Next() {
		var i ListLiftHistoryRow
		if err := rows.Scan(&i.PerformedOn, &i.WeightLb, &i.Success); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrescriptionsByDay = `-- name: ListPrescriptionsByDay :many
SELECT pde.id,
       pde.program_day_id,
       pde.exercise_id,
       e.name AS exercise_name,
       pde.position,
       pde.sets,
       pde.reps,
       pde.starting_weight_lb
FROM program_day_exercises pde
JOIN exercises e ON e.id = pde.exercise_id
WHERE pde.program_day_id = $1
ORDER BY pde.position
`

type ListPrescriptionsByDayRow struct {
	ID               int32          `json:"id"`
	ProgramDayID     int32          `json:"program_day_id"`
	ExerciseID       int32          `json:"exercise_id"`
	ExerciseName     string         `json:"exercise_name"`
	Position         int32          `json:"position"`
	Sets             int32          `json:"sets"`
	Reps             int32          `json:"reps"`
	StartingWeightLb pgtype.Numeric `json:"starting_weight_lb"`
}

// ListPrescriptionsByDay returns the prescribed exercises for a single day.
func (q *Queries) ListPrescriptionsByDay(ctx context.Context, programDayID int32) ([]ListPrescriptionsByDayRow, error) {
	rows, err := q.db.Query(ctx, listPrescriptionsByDay, programDayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrescriptionsByDayRow
	for rows.Next() {
		var i ListPrescriptionsByDayRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramDayID,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.Position,
			&i.Sets,
			&i.Reps,
			&i.StartingWeightLb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrescriptionsByProgram = `-- name: ListPrescriptionsByProgram :many
SELECT pde.id,
       pde.program_day_id,
       pde.exercise_id,
       e.name AS exercise_name,
       pde.position,
       pde.sets,
       pde.reps,
       pde.starting_weight_lb
FROM program_day_exercises pde
JOIN program_days pd ON pd.id = pde.program_day_id
JOIN exercises e ON e.id = pde.exercise_id
WHERE pd.program_id = $1
ORDER BY pd.position, pde.position
`

type ListPrescriptionsByProgramRow struct {
	ID               int32          `json:"id"`
	ProgramDayID     int32          `json:"program_day_id"`
	ExerciseID       int32          `json:"exercise_id"`
	ExerciseName     string         `json:"exercise_name"`
	Position         int32          `json:"position"`
	Sets             int32          `json:"sets"`
	Reps             int32          `json:"reps"`
	StartingWeightLb pgtype.Numeric `json:"starting_weight_lb"`
}

// ListPrescriptionsByProgram returns every prescribed exercise across all of a
// program's days, joined to the exercise name, ordered for assembly in Go.
func (q *Queries) ListPrescriptionsByProgram(ctx context.Context, programID int32) ([]ListPrescriptionsByProgramRow, error) {
	rows, err := q.db.Query(ctx, listPrescriptionsByProgram, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrescriptionsByProgramRow
	for rows.Next() {
		var i ListPrescriptionsByProgramRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramDayID,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.Position,
			&i.Sets,
			&i.Reps,
			&i.StartingWeightLb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramDays = `-- name: ListProgramDays :many
SELECT id, program_id, name, position
FROM program_days
WHERE program_id = $1
ORDER BY position
`

func (q *Queries) ListProgramDays(ctx context.Context, programID int32) ([]ProgramDay, error) {
	rows, err := q.db.Query(ctx, listProgramDays, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProgramDay
	for rows.Next() {
		var i ProgramDay
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.Name,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrograms = `-- name: ListPrograms :many
SELECT id, name, description, progression_kind
FROM programs
ORDER BY id
`

type ListProgramsRow struct {
	ID              int32  `json:"id"`
	Name            string `json:"name"`
	Description     string `json:"description"`
	ProgressionKind string `json:"progression_kind"`
}

func (q *Queries) ListPrograms(ctx context.Context) ([]ListProgramsRow, error) {
	rows, err := q.db.Query(ctx, listPrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProgramsRow
	for rows.Next() {
		var i ListProgramsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ProgressionKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
