// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: programs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProgram = `-- name: GetProgram :one
SELECT id, name, description, progression_kind
FROM programs
WHERE id = $1
`

type GetProgramRow struct {
	ID              int32  `json:"id"`
	Name            string `json:"name"`
	Description     string `json:"description"`
	ProgressionKind string `json:"progression_kind"`
}

func (q *Queries) GetProgram(ctx context.Context, id int32) (GetProgramRow, error) {
	row := q.db.QueryRow(ctx, getProgram, id)
	var i GetProgramRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ProgressionKind,
	)
	return i, err
}

const getProgramDay = `-- name: GetProgramDay :one
SELECT id, program_id, name, position, weekday
FROM program_days
WHERE id = $1
`

func (q *Queries) GetProgramDay(ctx context.Context, id int32) (ProgramDay, error) {
	row := q.db.QueryRow(ctx, getProgramDay, id)
	var i ProgramDay
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.Name,
		&i.Position,
		&i.Weekday,
	)
	return i, err
}

const listLiftHistory = `-- name: ListLiftHistory :many
SELECT s.performed_on,
       MAX(ss.weight_lb)::numeric  AS weight_lb,
       BOOL_AND(ss.completed)      AS success
FROM sessions s
JOIN session_sets ss ON ss.session_id = s.id
WHERE ss.exercise_id = $1
  AND s.user_id = $2::int
  AND (s.finished_at IS NOT NULL
       OR s.created_at < now() - INTERVAL '12 hours')
GROUP BY s.id, s.performed_on
HAVING COUNT(ss.id) FILTER (WHERE ss.actual_reps > 0) > 0
ORDER BY s.performed_on, s.id
`

type ListLiftHistoryParams struct {
	ExerciseID int32 `json:"exercise_id"`
	UserID     int32 `json:"user_id"`
}

type ListLiftHistoryRow struct {
	PerformedOn pgtype.Date    `json:"performed_on"`
	WeightLb    pgtype.Numeric `json:"weight_lb"`
	Success     bool           `json:"success"`
}

// ListLiftHistory returns one row per past session in which a lift was
// performed, oldest first, for the progression engine. A session "succeeds" for
// the lift only if every logged set for it was completed; weight_lb is the top
// weight worked that session.
//
// Scope is the lift and the lifter, deliberately NOT the program. A squat is a
// squat: the bar does not know which program day sent you to it, and neither
// should the engine. Scoping this to one program used to mean that switching
// programs restarted every lift at its seeded starting weight — which fell
// hardest on exactly the move the app recommends, since Advanced 3x5 is the
// graduation fork when 5x5 stalls and taking it dropped a working squat back to
// an empty bar. ListExerciseHistory has always read across programs for the
// same reason (assistance.sql calls it "dips are dips whichever day they were
// done on"); this is the main lifts agreeing with it.
//
// The consequence to keep in mind: a lift's history is now one series, so a
// deload or a stall follows you between programs as well. That is the intent —
// a stall is a fact about the lifter, not about the program they were running
// when it happened.
//
// Only sessions that are over and carry real logged work count. Sets are
// materialized up front with completed = false, so without both guards a
// session you merely started — or are still in the middle of — would score as
// BOOL_AND(completed) = false and be recorded as a failed session, pushing the
// engine toward an unearned deload. See the is_over note in sessions.sql.
//
// The user_id filter matters more here than anywhere else: this feeds the
// progression engine, so an unscoped history would compute one lifter's next
// working weight from another's performance — a wrong number on the bar, not
// merely a privacy leak.
func (q *Queries) ListLiftHistory(ctx context.Context, arg ListLiftHistoryParams) ([]ListLiftHistoryRow, error) {
	rows, err := q.db.Query(ctx, listLiftHistory, arg.ExerciseID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiftHistoryRow
	for rows.Next() {
		var i ListLiftHistoryRow
		if err := rows.Scan(&i.PerformedOn, &i.WeightLb, &i.Success); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiftHistoryForDay = `-- name: ListLiftHistoryForDay :many
SELECT s.performed_on,
       MAX(ss.weight_lb)::numeric  AS weight_lb,
       BOOL_AND(ss.completed)      AS success
FROM sessions s
JOIN session_sets ss ON ss.session_id = s.id
WHERE ss.exercise_id = $1
  AND s.user_id = $2::int
  AND s.program_day_id = $3
  AND (s.finished_at IS NOT NULL
       OR s.created_at < now() - INTERVAL '12 hours')
GROUP BY s.id, s.performed_on
HAVING COUNT(ss.id) FILTER (WHERE ss.actual_reps > 0) > 0
ORDER BY s.performed_on, s.id
`

type ListLiftHistoryForDayParams struct {
	ExerciseID   int32 `json:"exercise_id"`
	UserID       int32 `json:"user_id"`
	ProgramDayID int32 `json:"program_day_id"`
}

type ListLiftHistoryForDayRow struct {
	PerformedOn pgtype.Date    `json:"performed_on"`
	WeightLb    pgtype.Numeric `json:"weight_lb"`
	Success     bool           `json:"success"`
}

// ListLiftHistoryForDay is ListLiftHistory narrowed to one program day, for the
// Madcow engine's top set.
//
// The narrowing is the whole point and is not an optimisation. A lift's top set
// is decided on its reference day alone: the squat's ramp tops at 87.5% on the
// light day and 102.5% on the intensity day, so a history taking every day's
// heaviest set would see the number wander and read it as progress and regress
// that never happened.
//
// Same is_over and actual_reps guards as ListLiftHistory, for the same reasons —
// see the note there, which this query is otherwise a copy of.
func (q *Queries) ListLiftHistoryForDay(ctx context.Context, arg ListLiftHistoryForDayParams) ([]ListLiftHistoryForDayRow, error) {
	rows, err := q.db.Query(ctx, listLiftHistoryForDay, arg.ExerciseID, arg.UserID, arg.ProgramDayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiftHistoryForDayRow
	for rows.Next() {
		var i ListLiftHistoryForDayRow
		if err := rows.Scan(&i.PerformedOn, &i.WeightLb, &i.Success); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrescriptionsByDay = `-- name: ListPrescriptionsByDay :many
SELECT pde.id,
       pde.program_day_id,
       pde.exercise_id,
       e.name AS exercise_name,
       pde.position,
       pde.sets,
       pde.reps,
       pde.starting_weight_lb,
       e.rest_seconds
FROM program_day_exercises pde
JOIN exercises e ON e.id = pde.exercise_id
WHERE pde.program_day_id = $1
ORDER BY pde.position
`

type ListPrescriptionsByDayRow struct {
	ID               int32          `json:"id"`
	ProgramDayID     int32          `json:"program_day_id"`
	ExerciseID       int32          `json:"exercise_id"`
	ExerciseName     string         `json:"exercise_name"`
	Position         int32          `json:"position"`
	Sets             int32          `json:"sets"`
	Reps             int32          `json:"reps"`
	StartingWeightLb pgtype.Numeric `json:"starting_weight_lb"`
	RestSeconds      int32          `json:"rest_seconds"`
}

// ListPrescriptionsByDay returns the prescribed exercises for a single day.
func (q *Queries) ListPrescriptionsByDay(ctx context.Context, programDayID int32) ([]ListPrescriptionsByDayRow, error) {
	rows, err := q.db.Query(ctx, listPrescriptionsByDay, programDayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrescriptionsByDayRow
	for rows.Next() {
		var i ListPrescriptionsByDayRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramDayID,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.Position,
			&i.Sets,
			&i.Reps,
			&i.StartingWeightLb,
			&i.RestSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrescriptionsByProgram = `-- name: ListPrescriptionsByProgram :many
SELECT pde.id,
       pde.program_day_id,
       pde.exercise_id,
       e.name AS exercise_name,
       pde.position,
       pde.sets,
       pde.reps,
       pde.starting_weight_lb,
       e.rest_seconds
FROM program_day_exercises pde
JOIN program_days pd ON pd.id = pde.program_day_id
JOIN exercises e ON e.id = pde.exercise_id
WHERE pd.program_id = $1
ORDER BY pd.position, pde.position
`

type ListPrescriptionsByProgramRow struct {
	ID               int32          `json:"id"`
	ProgramDayID     int32          `json:"program_day_id"`
	ExerciseID       int32          `json:"exercise_id"`
	ExerciseName     string         `json:"exercise_name"`
	Position         int32          `json:"position"`
	Sets             int32          `json:"sets"`
	Reps             int32          `json:"reps"`
	StartingWeightLb pgtype.Numeric `json:"starting_weight_lb"`
	RestSeconds      int32          `json:"rest_seconds"`
}

// ListPrescriptionsByProgram returns every prescribed exercise across all of a
// program's days, joined to the exercise name, ordered for assembly in Go.
//
// rest_seconds comes off the exercise rather than the prescription: rest is a
// property of the movement, so a squat rests the same on Workout A and B. See
// 0011 for the tiers.
func (q *Queries) ListPrescriptionsByProgram(ctx context.Context, programID int32) ([]ListPrescriptionsByProgramRow, error) {
	rows, err := q.db.Query(ctx, listPrescriptionsByProgram, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrescriptionsByProgramRow
	for rows.Next() {
		var i ListPrescriptionsByProgramRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramDayID,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.Position,
			&i.Sets,
			&i.Reps,
			&i.StartingWeightLb,
			&i.RestSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramDays = `-- name: ListProgramDays :many
SELECT id, program_id, name, position, weekday
FROM program_days
WHERE program_id = $1
ORDER BY position
`

func (q *Queries) ListProgramDays(ctx context.Context, programID int32) ([]ProgramDay, error) {
	rows, err := q.db.Query(ctx, listProgramDays, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProgramDay
	for rows.Next() {
		var i ProgramDay
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.Name,
			&i.Position,
			&i.Weekday,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrograms = `-- name: ListPrograms :many
SELECT id, name, description, progression_kind
FROM programs
ORDER BY id
`

type ListProgramsRow struct {
	ID              int32  `json:"id"`
	Name            string `json:"name"`
	Description     string `json:"description"`
	ProgressionKind string `json:"progression_kind"`
}

func (q *Queries) ListPrograms(ctx context.Context) ([]ListProgramsRow, error) {
	rows, err := q.db.Query(ctx, listPrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProgramsRow
	for rows.Next() {
		var i ListProgramsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ProgressionKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProgramDayWeekday = `-- name: UpdateProgramDayWeekday :one
UPDATE program_days
SET weekday = $1
WHERE id = $2
RETURNING id, program_id, name, position, weekday
`

type UpdateProgramDayWeekdayParams struct {
	Weekday *int32 `json:"weekday"`
	ID      int32  `json:"id"`
}

func (q *Queries) UpdateProgramDayWeekday(ctx context.Context, arg UpdateProgramDayWeekdayParams) (ProgramDay, error) {
	row := q.db.QueryRow(ctx, updateProgramDayWeekday, arg.Weekday, arg.ID)
	var i ProgramDay
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.Name,
		&i.Position,
		&i.Weekday,
	)
	return i, err
}

const listSetPlansByProgram = `-- name: ListSetPlansByProgram :many
SELECT pde.program_day_id,
       pde.exercise_id,
       s.set_number,
       s.reps,
       s.pct_of_top
FROM program_day_exercise_sets s
JOIN program_day_exercises pde ON pde.id = s.program_day_exercise_id
JOIN program_days pd ON pd.id = pde.program_day_id
WHERE pd.program_id = $1
ORDER BY pde.program_day_id, pde.exercise_id, s.set_number
`

type ListSetPlansByProgramRow struct {
	ProgramDayID int32          `json:"program_day_id"`
	ExerciseID   int32          `json:"exercise_id"`
	SetNumber    int32          `json:"set_number"`
	Reps         int32          `json:"reps"`
	PctOfTop     pgtype.Numeric `json:"pct_of_top"`
}

// ListSetPlansByProgram returns every per-set prescription in a program, so a
// day's ramps and its lifts' reference days can both be resolved without a query
// per lift.
//
// Scoped to the program rather than to the day because the two questions have
// different scopes: what to load TODAY needs this day's rungs, but which day is
// a lift's reference needs every day's. Reading the program once answers both.
//
// Empty for every program but Madcow. An absent set plan means a uniform block
// of sets x reps at one weight, which is what the other five prescribe.
func (q *Queries) ListSetPlansByProgram(ctx context.Context, programID int32) ([]ListSetPlansByProgramRow, error) {
	rows, err := q.db.Query(ctx, listSetPlansByProgram, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSetPlansByProgramRow
	for rows.Next() {
		var i ListSetPlansByProgramRow
		if err := rows.Scan(
			&i.ProgramDayID,
			&i.ExerciseID,
			&i.SetNumber,
			&i.Reps,
			&i.PctOfTop,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
