// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSessions = `-- name: CountSessions :one
SELECT COUNT(*) AS total
FROM sessions s
JOIN program_days pd ON pd.id = s.program_day_id
WHERE ($1::bigint IS NULL OR pd.program_id = $1)
`

func (q *Queries) CountSessions(ctx context.Context, programID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countSessions, programID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (program_day_id, performed_on)
VALUES ($1, $2)
RETURNING id, program_day_id, performed_on, notes, created_at
`

type CreateSessionParams struct {
	ProgramDayID int32       `json:"program_day_id"`
	PerformedOn  pgtype.Date `json:"performed_on"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.ProgramDayID, arg.PerformedOn)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProgramDayID,
		&i.PerformedOn,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createSessionSet = `-- name: CreateSessionSet :one
INSERT INTO session_sets (session_id, exercise_id, set_number, target_reps, weight_lb)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, session_id, exercise_id, set_number, target_reps, actual_reps, weight_lb, completed
`

type CreateSessionSetParams struct {
	SessionID  int32          `json:"session_id"`
	ExerciseID int32          `json:"exercise_id"`
	SetNumber  int32          `json:"set_number"`
	TargetReps int32          `json:"target_reps"`
	WeightLb   pgtype.Numeric `json:"weight_lb"`
}

func (q *Queries) CreateSessionSet(ctx context.Context, arg CreateSessionSetParams) (SessionSet, error) {
	row := q.db.QueryRow(ctx, createSessionSet,
		arg.SessionID,
		arg.ExerciseID,
		arg.SetNumber,
		arg.TargetReps,
		arg.WeightLb,
	)
	var i SessionSet
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ExerciseID,
		&i.SetNumber,
		&i.TargetReps,
		&i.ActualReps,
		&i.WeightLb,
		&i.Completed,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSession = `-- name: GetSession :one
SELECT s.id,
       s.program_day_id,
       pd.name AS program_day_name,
       p.id    AS program_id,
       p.name  AS program_name,
       s.performed_on,
       s.notes,
       s.created_at
FROM sessions s
JOIN program_days pd ON pd.id = s.program_day_id
JOIN programs p ON p.id = pd.program_id
WHERE s.id = $1
`

type GetSessionRow struct {
	ID             int32              `json:"id"`
	ProgramDayID   int32              `json:"program_day_id"`
	ProgramDayName string             `json:"program_day_name"`
	ProgramID      int32              `json:"program_id"`
	ProgramName    string             `json:"program_name"`
	PerformedOn    pgtype.Date        `json:"performed_on"`
	Notes          string             `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetSession(ctx context.Context, id int32) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.ProgramDayID,
		&i.ProgramDayName,
		&i.ProgramID,
		&i.ProgramName,
		&i.PerformedOn,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionSet = `-- name: GetSessionSet :one
SELECT ss.id,
       ss.session_id,
       ss.exercise_id,
       e.name AS exercise_name,
       ss.set_number,
       ss.target_reps,
       ss.actual_reps,
       ss.weight_lb,
       ss.completed
FROM session_sets ss
JOIN exercises e ON e.id = ss.exercise_id
WHERE ss.id = $1
`

type GetSessionSetRow struct {
	ID           int32          `json:"id"`
	SessionID    int32          `json:"session_id"`
	ExerciseID   int32          `json:"exercise_id"`
	ExerciseName string         `json:"exercise_name"`
	SetNumber    int32          `json:"set_number"`
	TargetReps   int32          `json:"target_reps"`
	ActualReps   *int32         `json:"actual_reps"`
	WeightLb     pgtype.Numeric `json:"weight_lb"`
	Completed    bool           `json:"completed"`
}

func (q *Queries) GetSessionSet(ctx context.Context, id int32) (GetSessionSetRow, error) {
	row := q.db.QueryRow(ctx, getSessionSet, id)
	var i GetSessionSetRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ExerciseID,
		&i.ExerciseName,
		&i.SetNumber,
		&i.TargetReps,
		&i.ActualReps,
		&i.WeightLb,
		&i.Completed,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT s.id,
       s.program_day_id,
       pd.name AS program_day_name,
       p.id    AS program_id,
       p.name  AS program_name,
       s.performed_on,
       COUNT(ss.id)                              AS set_count,
       COUNT(ss.id) FILTER (WHERE ss.completed)  AS completed_set_count
FROM sessions s
JOIN program_days pd ON pd.id = s.program_day_id
JOIN programs p ON p.id = pd.program_id
LEFT JOIN session_sets ss ON ss.session_id = s.id
WHERE ($1::bigint IS NULL OR p.id = $1)
GROUP BY s.id, pd.name, p.id, p.name
ORDER BY s.performed_on DESC, s.id DESC
LIMIT $3 OFFSET $2
`

type ListSessionsParams struct {
	ProgramID *int64 `json:"program_id"`
	Off       int32  `json:"off"`
	Lim       int32  `json:"lim"`
}

type ListSessionsRow struct {
	ID                int32       `json:"id"`
	ProgramDayID      int32       `json:"program_day_id"`
	ProgramDayName    string      `json:"program_day_name"`
	ProgramID         int32       `json:"program_id"`
	ProgramName       string      `json:"program_name"`
	PerformedOn       pgtype.Date `json:"performed_on"`
	SetCount          int64       `json:"set_count"`
	CompletedSetCount int64       `json:"completed_set_count"`
}

// ListSessions returns paginated session summaries, most recent first,
// optionally filtered to one program. Pass NULL program_id for all programs.
func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]ListSessionsRow, error) {
	rows, err := q.db.Query(ctx, listSessions, arg.ProgramID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsRow
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramDayID,
			&i.ProgramDayName,
			&i.ProgramID,
			&i.ProgramName,
			&i.PerformedOn,
			&i.SetCount,
			&i.CompletedSetCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET performed_on = COALESCE($1, performed_on),
    notes        = COALESCE($2, notes)
WHERE id = $3
RETURNING id, program_day_id, performed_on, notes, created_at
`

type UpdateSessionParams struct {
	PerformedOn pgtype.Date `json:"performed_on"`
	Notes       *string     `json:"notes"`
	ID          int32       `json:"id"`
}

// UpdateSession patches metadata; NULL args leave a column unchanged.
func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSession, arg.PerformedOn, arg.Notes, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProgramDayID,
		&i.PerformedOn,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const updateSessionSet = `-- name: UpdateSessionSet :one
UPDATE session_sets
SET actual_reps = $1,
    weight_lb   = $2,
    completed   = $3
WHERE id = $4
RETURNING id, session_id, exercise_id, set_number, target_reps, actual_reps, weight_lb, completed
`

type UpdateSessionSetParams struct {
	ActualReps *int32         `json:"actual_reps"`
	WeightLb   pgtype.Numeric `json:"weight_lb"`
	Completed  bool           `json:"completed"`
	ID         int32          `json:"id"`
}

// UpdateSessionSet writes all three mutable columns; the handler merges the
// PATCH body with current values first, so actual_reps can be set to NULL to
// clear a prior entry (COALESCE could not express that).
func (q *Queries) UpdateSessionSet(ctx context.Context, arg UpdateSessionSetParams) (SessionSet, error) {
	row := q.db.QueryRow(ctx, updateSessionSet,
		arg.ActualReps,
		arg.WeightLb,
		arg.Completed,
		arg.ID,
	)
	var i SessionSet
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ExerciseID,
		&i.SetNumber,
		&i.TargetReps,
		&i.ActualReps,
		&i.WeightLb,
		&i.Completed,
	)
	return i, err
}
