// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSessions = `-- name: CountSessions :one
SELECT COUNT(*) AS total
FROM sessions s
JOIN program_days pd ON pd.id = s.program_day_id
WHERE s.user_id = $1::int
  AND ($2::bigint IS NULL OR pd.program_id = $2)
  AND EXISTS (
    SELECT 1 FROM session_sets ls
    WHERE ls.session_id = s.id AND ls.actual_reps > 0
  )
`

type CountSessionsParams struct {
	UserID    int32  `json:"user_id"`
	ProgramID *int64 `json:"program_id"`
}

func (q *Queries) CountSessions(ctx context.Context, arg CountSessionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSessions, arg.UserID, arg.ProgramID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (program_day_id, performed_on, user_id)
VALUES ($1, $2, $3::int)
RETURNING id, program_day_id, performed_on, notes, created_at, finished_at, user_id
`

type CreateSessionParams struct {
	ProgramDayID int32       `json:"program_day_id"`
	PerformedOn  pgtype.Date `json:"performed_on"`
	UserID       int32       `json:"user_id"`
}

// A session is "over" when the lifter finished it by hand, or when it was
// started more than 12 hours ago and so cannot still be in progress. This is
// derived at read time rather than materialized: no background job has to run,
// and there is no window in which a stale row disagrees with the clock. The
// expression is repeated in the queries below because a generated column cannot
// use now(), which Postgres does not consider immutable. Keep the copies in
// sync — GetSession, ListSessions and ListLiftHistory all depend on it.
//
//	s.finished_at IS NOT NULL OR s.created_at < now() - INTERVAL '12 hours'
//
// Every query here is scoped to one owner (s.user_id = user_id). That filter is
// the whole of the isolation model, so it is not optional on any read or write:
// programs and exercises are shared, but performances are not. A session the
// caller does not own must be indistinguishable from one that does not exist,
// which is why the set-level queries below reach the owner through a JOIN back
// to sessions rather than trusting the set id alone — a caller learning that
// someone else's set id is valid is already a leak.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.ProgramDayID, arg.PerformedOn, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProgramDayID,
		&i.PerformedOn,
		&i.Notes,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.UserID,
	)
	return i, err
}

const createSessionSet = `-- name: CreateSessionSet :one
INSERT INTO session_sets (session_id, exercise_id, set_number, target_reps, weight_lb)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, session_id, exercise_id, set_number, target_reps, actual_reps, weight_lb, completed
`

type CreateSessionSetParams struct {
	SessionID  int32          `json:"session_id"`
	ExerciseID int32          `json:"exercise_id"`
	SetNumber  int32          `json:"set_number"`
	TargetReps int32          `json:"target_reps"`
	WeightLb   pgtype.Numeric `json:"weight_lb"`
}

func (q *Queries) CreateSessionSet(ctx context.Context, arg CreateSessionSetParams) (SessionSet, error) {
	row := q.db.QueryRow(ctx, createSessionSet,
		arg.SessionID,
		arg.ExerciseID,
		arg.SetNumber,
		arg.TargetReps,
		arg.WeightLb,
	)
	var i SessionSet
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ExerciseID,
		&i.SetNumber,
		&i.TargetReps,
		&i.ActualReps,
		&i.WeightLb,
		&i.Completed,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions
WHERE id = $1
  AND user_id = $2::int
`

type DeleteSessionParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishSession = `-- name: FinishSession :one
UPDATE sessions
SET finished_at = COALESCE(finished_at, now())
WHERE id = $1
  AND user_id = $2::int
RETURNING id, program_day_id, performed_on, notes, created_at, finished_at, user_id
`

type FinishSessionParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

// FinishSession stamps the explicit end of a session. COALESCE makes it
// idempotent: finishing an already-finished session keeps the original time
// rather than sliding it forward on a double-tap.
func (q *Queries) FinishSession(ctx context.Context, arg FinishSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, finishSession, arg.ID, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProgramDayID,
		&i.PerformedOn,
		&i.Notes,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.UserID,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT s.id,
       s.program_day_id,
       pd.name AS program_day_name,
       p.id    AS program_id,
       p.name  AS program_name,
       s.performed_on,
       s.notes,
       s.created_at,
       s.finished_at,
       (s.finished_at IS NOT NULL
        OR s.created_at < now() - INTERVAL '12 hours')::bool AS is_over
FROM sessions s
JOIN program_days pd ON pd.id = s.program_day_id
JOIN programs p ON p.id = pd.program_id
WHERE s.id = $1
  AND s.user_id = $2::int
`

type GetSessionParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

type GetSessionRow struct {
	ID             int32              `json:"id"`
	ProgramDayID   int32              `json:"program_day_id"`
	ProgramDayName string             `json:"program_day_name"`
	ProgramID      int32              `json:"program_id"`
	ProgramName    string             `json:"program_name"`
	PerformedOn    pgtype.Date        `json:"performed_on"`
	Notes          string             `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	IsOver         bool               `json:"is_over"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, arg.ID, arg.UserID)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.ProgramDayID,
		&i.ProgramDayName,
		&i.ProgramID,
		&i.ProgramName,
		&i.PerformedOn,
		&i.Notes,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.IsOver,
	)
	return i, err
}

const getSessionSet = `-- name: GetSessionSet :one
SELECT ss.id,
       ss.session_id,
       ss.exercise_id,
       e.name AS exercise_name,
       ss.set_number,
       ss.target_reps,
       ss.actual_reps,
       ss.weight_lb,
       ss.completed
FROM session_sets ss
JOIN exercises e ON e.id = ss.exercise_id
JOIN sessions s ON s.id = ss.session_id
WHERE ss.id = $1
  AND s.user_id = $2::int
`

type GetSessionSetParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

type GetSessionSetRow struct {
	ID           int32          `json:"id"`
	SessionID    int32          `json:"session_id"`
	ExerciseID   int32          `json:"exercise_id"`
	ExerciseName string         `json:"exercise_name"`
	SetNumber    int32          `json:"set_number"`
	TargetReps   int32          `json:"target_reps"`
	ActualReps   *int32         `json:"actual_reps"`
	WeightLb     pgtype.Numeric `json:"weight_lb"`
	Completed    bool           `json:"completed"`
}

// GetSessionSet reaches the owner through session_sets -> sessions, so a set id
// belonging to someone else simply does not resolve.
func (q *Queries) GetSessionSet(ctx context.Context, arg GetSessionSetParams) (GetSessionSetRow, error) {
	row := q.db.QueryRow(ctx, getSessionSet, arg.ID, arg.UserID)
	var i GetSessionSetRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ExerciseID,
		&i.ExerciseName,
		&i.SetNumber,
		&i.TargetReps,
		&i.ActualReps,
		&i.WeightLb,
		&i.Completed,
	)
	return i, err
}

const listSessionExerciseWeights = `-- name: ListSessionExerciseWeights :many
SELECT ss.session_id,
       e.name                      AS exercise_name,
       COUNT(ss.id)                AS set_count,
       MAX(ss.target_reps)::int    AS reps,
       MAX(ss.weight_lb)::numeric  AS weight_lb
FROM session_sets ss
JOIN exercises e ON e.id = ss.exercise_id
JOIN sessions s ON s.id = ss.session_id
JOIN program_day_exercises pde
  ON pde.program_day_id = s.program_day_id AND pde.exercise_id = ss.exercise_id
WHERE ss.session_id = ANY($1::int[])
  AND s.user_id = $2::int
GROUP BY ss.session_id, e.name
ORDER BY ss.session_id, MIN(pde.position)
`

type ListSessionExerciseWeightsParams struct {
	SessionIds []int32 `json:"session_ids"`
	UserID     int32   `json:"user_id"`
}

type ListSessionExerciseWeightsRow struct {
	SessionID    int32          `json:"session_id"`
	ExerciseName string         `json:"exercise_name"`
	SetCount     int64          `json:"set_count"`
	Reps         int32          `json:"reps"`
	WeightLb     pgtype.Numeric `json:"weight_lb"`
}

// ListSessionExerciseWeights returns each exercise's top working weight for the
// given sessions, ordered by the day's exercise position — used to show a
// per-lift weight line on each history row.
func (q *Queries) ListSessionExerciseWeights(ctx context.Context, arg ListSessionExerciseWeightsParams) ([]ListSessionExerciseWeightsRow, error) {
	rows, err := q.db.Query(ctx, listSessionExerciseWeights, arg.SessionIds, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionExerciseWeightsRow
	for rows.Next() {
		var i ListSessionExerciseWeightsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.ExerciseName,
			&i.SetCount,
			&i.Reps,
			&i.WeightLb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionSets = `-- name: ListSessionSets :many
SELECT ss.id,
       ss.session_id,
       ss.exercise_id,
       e.name AS exercise_name,
       ss.set_number,
       ss.target_reps,
       ss.actual_reps,
       ss.weight_lb,
       ss.completed
FROM session_sets ss
JOIN exercises e ON e.id = ss.exercise_id
JOIN sessions s ON s.id = ss.session_id
JOIN program_day_exercises pde
  ON pde.program_day_id = s.program_day_id AND pde.exercise_id = ss.exercise_id
WHERE ss.session_id = $1
  AND s.user_id = $2::int
ORDER BY pde.position, ss.set_number
`

type ListSessionSetsParams struct {
	SessionID int32 `json:"session_id"`
	UserID    int32 `json:"user_id"`
}

type ListSessionSetsRow struct {
	ID           int32          `json:"id"`
	SessionID    int32          `json:"session_id"`
	ExerciseID   int32          `json:"exercise_id"`
	ExerciseName string         `json:"exercise_name"`
	SetNumber    int32          `json:"set_number"`
	TargetReps   int32          `json:"target_reps"`
	ActualReps   *int32         `json:"actual_reps"`
	WeightLb     pgtype.Numeric `json:"weight_lb"`
	Completed    bool           `json:"completed"`
}

// ListSessionSets returns a session's logged sets in prescription order
// (by the day's exercise position, then set number), joined to exercise names.
func (q *Queries) ListSessionSets(ctx context.Context, arg ListSessionSetsParams) ([]ListSessionSetsRow, error) {
	rows, err := q.db.Query(ctx, listSessionSets, arg.SessionID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionSetsRow
	for rows.Next() {
		var i ListSessionSetsRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.SetNumber,
			&i.TargetReps,
			&i.ActualReps,
			&i.WeightLb,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT s.id,
       s.program_day_id,
       pd.name AS program_day_name,
       p.id    AS program_id,
       p.name  AS program_name,
       s.performed_on,
       COUNT(ss.id)                              AS set_count,
       COUNT(ss.id) FILTER (WHERE ss.completed)  AS completed_set_count,
       (s.finished_at IS NOT NULL
        OR s.created_at < now() - INTERVAL '12 hours')::bool AS is_over
FROM sessions s
JOIN program_days pd ON pd.id = s.program_day_id
JOIN programs p ON p.id = pd.program_id
LEFT JOIN session_sets ss ON ss.session_id = s.id
WHERE s.user_id = $1::int
  AND ($2::bigint IS NULL OR p.id = $2)
GROUP BY s.id, pd.name, p.id, p.name
HAVING COUNT(ss.id) FILTER (WHERE ss.actual_reps > 0) > 0
ORDER BY s.performed_on DESC, s.id DESC
LIMIT $4 OFFSET $3
`

type ListSessionsParams struct {
	UserID    int32  `json:"user_id"`
	ProgramID *int64 `json:"program_id"`
	Off       int32  `json:"off"`
	Lim       int32  `json:"lim"`
}

type ListSessionsRow struct {
	ID                int32       `json:"id"`
	ProgramDayID      int32       `json:"program_day_id"`
	ProgramDayName    string      `json:"program_day_name"`
	ProgramID         int32       `json:"program_id"`
	ProgramName       string      `json:"program_name"`
	PerformedOn       pgtype.Date `json:"performed_on"`
	SetCount          int64       `json:"set_count"`
	CompletedSetCount int64       `json:"completed_set_count"`
	IsOver            bool        `json:"is_over"`
}

// ListSessions returns paginated session summaries, most recent first,
// optionally filtered to one program. Pass NULL program_id for all programs.
// is_over reads s.finished_at/s.created_at under a GROUP BY: legal because the
// grouping includes s.id, the primary key, which makes every other sessions
// column functionally dependent on it.
// Only sessions with at least one logged rep count as "started".
func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]ListSessionsRow, error) {
	rows, err := q.db.Query(ctx, listSessions,
		arg.UserID,
		arg.ProgramID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsRow
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramDayID,
			&i.ProgramDayName,
			&i.ProgramID,
			&i.ProgramName,
			&i.PerformedOn,
			&i.SetCount,
			&i.CompletedSetCount,
			&i.IsOver,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET performed_on = COALESCE($1, performed_on),
    notes        = COALESCE($2, notes)
WHERE id = $3
  AND user_id = $4::int
RETURNING id, program_day_id, performed_on, notes, created_at, finished_at, user_id
`

type UpdateSessionParams struct {
	PerformedOn pgtype.Date `json:"performed_on"`
	Notes       *string     `json:"notes"`
	ID          int32       `json:"id"`
	UserID      int32       `json:"user_id"`
}

// UpdateSession patches metadata; NULL args leave a column unchanged.
func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSession,
		arg.PerformedOn,
		arg.Notes,
		arg.ID,
		arg.UserID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProgramDayID,
		&i.PerformedOn,
		&i.Notes,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.UserID,
	)
	return i, err
}

const updateSessionSet = `-- name: UpdateSessionSet :one
UPDATE session_sets ss
SET actual_reps = $1,
    weight_lb   = $2,
    completed   = $3
FROM sessions s
WHERE ss.id = $4
  AND s.id = ss.session_id
  AND s.user_id = $5::int
RETURNING ss.id, ss.session_id, ss.exercise_id, ss.set_number, ss.target_reps, ss.actual_reps, ss.weight_lb, ss.completed
`

type UpdateSessionSetParams struct {
	ActualReps *int32         `json:"actual_reps"`
	WeightLb   pgtype.Numeric `json:"weight_lb"`
	Completed  bool           `json:"completed"`
	ID         int32          `json:"id"`
	UserID     int32          `json:"user_id"`
}

// UpdateSessionSet writes all three mutable columns; the handler merges the
// PATCH body with current values first, so actual_reps can be set to NULL to
// clear a prior entry (COALESCE could not express that). The owner check is
// repeated here rather than inferred from the preceding GetSessionSet: an
// UPDATE that trusts a prior read is one refactor away from trusting nothing.
func (q *Queries) UpdateSessionSet(ctx context.Context, arg UpdateSessionSetParams) (SessionSet, error) {
	row := q.db.QueryRow(ctx, updateSessionSet,
		arg.ActualReps,
		arg.WeightLb,
		arg.Completed,
		arg.ID,
		arg.UserID,
	)
	var i SessionSet
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ExerciseID,
		&i.SetNumber,
		&i.TargetReps,
		&i.ActualReps,
		&i.WeightLb,
		&i.Completed,
	)
	return i, err
}
