// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendSessionSet = `-- name: AppendSessionSet :one
INSERT INTO session_sets (session_id, exercise_id, set_number, target_reps, weight_lb)
SELECT last.session_id,
       last.exercise_id,
       last.set_number + 1,
       last.target_reps,
       last.weight_lb
FROM (
    SELECT ss.session_id, ss.exercise_id, ss.set_number, ss.target_reps, ss.weight_lb
    FROM session_sets ss
    JOIN sessions s ON s.id = ss.session_id
    WHERE ss.session_id = $1
      AND ss.exercise_id = $2
      AND s.user_id = $3::int
    ORDER BY ss.set_number DESC
    LIMIT 1
) AS last
RETURNING id, session_id, exercise_id, set_number, target_reps, actual_reps, weight_lb, completed
`

type AppendSessionSetParams struct {
	SessionID  int32 `json:"session_id"`
	ExerciseID int32 `json:"exercise_id"`
	UserID     int32 `json:"user_id"`
}

// AppendSessionSet adds one more set to a lift already in the session, copying
// the rep target and weight from that lift's current last set — an extra set is
// another set of the same thing, and anything else is what the weight stepper
// and the rep counter are for.
//
// set_number is MAX + 1, computed inside the INSERT rather than read and
// incremented by the handler: two concurrent taps that both read "5" would both
// write 6 and one would lose to session_sets' UNIQUE. Same argument
// CreateAssistance makes for position.
//
// Taking the last set by ORDER BY ... LIMIT 1 also means gaps are harmless: a
// deleted set leaves its number unused, and the next append lands past it rather
// than trying to fill it.
//
// Returns no rows when the lift is not in the session, which is how the handler
// tells a bad exerciseId from a real failure. Ownership and whether the session
// is still open are checked before this runs, so they are 404 and 409 rather
// than an indistinguishable empty result.
func (q *Queries) AppendSessionSet(ctx context.Context, arg AppendSessionSetParams) (SessionSet, error) {
	row := q.db.QueryRow(ctx, appendSessionSet, arg.SessionID, arg.ExerciseID, arg.UserID)
	var i SessionSet
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ExerciseID,
		&i.SetNumber,
		&i.TargetReps,
		&i.ActualReps,
		&i.WeightLb,
		&i.Completed,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (program_day_id, performed_on, user_id)
VALUES ($1, $2, $3::int)
RETURNING id, program_day_id, performed_on, notes, created_at, finished_at, user_id, bodyweight_lb
`

type CreateSessionParams struct {
	ProgramDayID int32       `json:"program_day_id"`
	PerformedOn  pgtype.Date `json:"performed_on"`
	UserID       int32       `json:"user_id"`
}

// A session is "over" when the lifter finished it by hand, or when it was
// started more than 12 hours ago and so cannot still be in progress. This is
// derived at read time rather than materialized: no background job has to run,
// and there is no window in which a stale row disagrees with the clock. The
// expression is repeated in the queries below because a generated column cannot
// use now(), which Postgres does not consider immutable. Keep the copies in
// sync — GetSession, ListSessions and ListLiftHistory all depend on it.
//
//	s.finished_at IS NOT NULL OR s.created_at < now() - INTERVAL '12 hours'
//
// Every query here is scoped to one owner (s.user_id = user_id). That filter is
// the whole of the isolation model, so it is not optional on any read or write:
// programs and exercises are shared, but performances are not. A session the
// caller does not own must be indistinguishable from one that does not exist,
// which is why the set-level queries below reach the owner through a JOIN back
// to sessions rather than trusting the set id alone — a caller learning that
// someone else's set id is valid is already a leak.
//
// The three RETURNING lists on sessions name every column of the table, in the
// table's own order, and that is deliberate: it is what makes sqlc reuse the
// Session model struct instead of emitting a bespoke row type per query. A
// column added to sessions has to be added to all three, or the next generation
// silently splits them apart.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.ProgramDayID, arg.PerformedOn, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProgramDayID,
		&i.PerformedOn,
		&i.Notes,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.UserID,
		&i.BodyweightLb,
	)
	return i, err
}

const createSessionSet = `-- name: CreateSessionSet :one
INSERT INTO session_sets (session_id, exercise_id, set_number, target_reps, weight_lb)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, session_id, exercise_id, set_number, target_reps, actual_reps, weight_lb, completed
`

type CreateSessionSetParams struct {
	SessionID  int32          `json:"session_id"`
	ExerciseID int32          `json:"exercise_id"`
	SetNumber  int32          `json:"set_number"`
	TargetReps int32          `json:"target_reps"`
	WeightLb   pgtype.Numeric `json:"weight_lb"`
}

func (q *Queries) CreateSessionSet(ctx context.Context, arg CreateSessionSetParams) (SessionSet, error) {
	row := q.db.QueryRow(ctx, createSessionSet,
		arg.SessionID,
		arg.ExerciseID,
		arg.SetNumber,
		arg.TargetReps,
		arg.WeightLb,
	)
	var i SessionSet
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ExerciseID,
		&i.SetNumber,
		&i.TargetReps,
		&i.ActualReps,
		&i.WeightLb,
		&i.Completed,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions
WHERE id = $1
  AND user_id = $2::int
`

type DeleteSessionParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionSet = `-- name: DeleteSessionSet :execrows
DELETE FROM session_sets ss
USING sessions s
WHERE ss.id = $1
  AND s.id = ss.session_id
  AND s.user_id = $2::int
`

type DeleteSessionSetParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

// DeleteSessionSet removes one set. Reaches the owner through sessions, the same
// way GetSessionSet does, so a set id belonging to someone else does not resolve
// rather than reporting a different failure.
//
// Nothing renumbers afterwards. set_number is ordering, not identity: every read
// here sorts by it and none of them assume it is dense, and renumbering inside
// UNIQUE (session_id, exercise_id, set_number) would need a deferred constraint
// to avoid colliding with itself mid-update. A gap costs nothing.
//
// Deleting a lift's last set is allowed, and takes the lift out of the session.
// That is a real thing to want — the rows were skipped — and it reads correctly
// everywhere downstream, since a lift with no sets simply has nothing to report.
func (q *Queries) DeleteSessionSet(ctx context.Context, arg DeleteSessionSetParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionSet, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishSession = `-- name: FinishSession :one
UPDATE sessions
SET finished_at = COALESCE(finished_at, now())
WHERE id = $1
  AND user_id = $2::int
RETURNING id, program_day_id, performed_on, notes, created_at, finished_at, user_id, bodyweight_lb
`

type FinishSessionParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

// FinishSession stamps the explicit end of a session. COALESCE makes it
// idempotent: finishing an already-finished session keeps the original time
// rather than sliding it forward on a double-tap.
func (q *Queries) FinishSession(ctx context.Context, arg FinishSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, finishSession, arg.ID, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProgramDayID,
		&i.PerformedOn,
		&i.Notes,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.UserID,
		&i.BodyweightLb,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT s.id,
       s.program_day_id,
       pd.name AS program_day_name,
       p.id    AS program_id,
       p.name  AS program_name,
       s.performed_on,
       s.notes,
       s.created_at,
       s.finished_at,
       s.bodyweight_lb,
       (s.finished_at IS NOT NULL
        OR s.created_at < now() - INTERVAL '12 hours')::bool AS is_over
FROM sessions s
JOIN program_days pd ON pd.id = s.program_day_id
JOIN programs p ON p.id = pd.program_id
WHERE s.id = $1
  AND s.user_id = $2::int
`

type GetSessionParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

type GetSessionRow struct {
	ID             int32              `json:"id"`
	ProgramDayID   int32              `json:"program_day_id"`
	ProgramDayName string             `json:"program_day_name"`
	ProgramID      int32              `json:"program_id"`
	ProgramName    string             `json:"program_name"`
	PerformedOn    pgtype.Date        `json:"performed_on"`
	Notes          string             `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	BodyweightLb   pgtype.Numeric     `json:"bodyweight_lb"`
	IsOver         bool               `json:"is_over"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, arg.ID, arg.UserID)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.ProgramDayID,
		&i.ProgramDayName,
		&i.ProgramID,
		&i.ProgramName,
		&i.PerformedOn,
		&i.Notes,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.BodyweightLb,
		&i.IsOver,
	)
	return i, err
}

const getSessionSet = `-- name: GetSessionSet :one
SELECT ss.id,
       ss.session_id,
       ss.exercise_id,
       e.name AS exercise_name,
       ss.set_number,
       ss.target_reps,
       ss.actual_reps,
       ss.weight_lb,
       ss.completed,
       (pde.id IS NULL)::bool AS is_assistance,
       e.rest_seconds
FROM session_sets ss
JOIN exercises e ON e.id = ss.exercise_id
JOIN sessions s ON s.id = ss.session_id
LEFT JOIN program_day_exercises pde
  ON pde.program_day_id = s.program_day_id AND pde.exercise_id = ss.exercise_id
WHERE ss.id = $1
  AND s.user_id = $2::int
`

type GetSessionSetParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

type GetSessionSetRow struct {
	ID           int32          `json:"id"`
	SessionID    int32          `json:"session_id"`
	ExerciseID   int32          `json:"exercise_id"`
	ExerciseName string         `json:"exercise_name"`
	SetNumber    int32          `json:"set_number"`
	TargetReps   int32          `json:"target_reps"`
	ActualReps   *int32         `json:"actual_reps"`
	WeightLb     pgtype.Numeric `json:"weight_lb"`
	Completed    bool           `json:"completed"`
	IsAssistance bool           `json:"is_assistance"`
	RestSeconds  int32          `json:"rest_seconds"`
}

// GetSessionSet reaches the owner through session_sets -> sessions, so a set id
// belonging to someone else simply does not resolve.
//
// is_assistance is derived the same way as in ListSessionSets — absence of a
// program_day_exercises row for the day — so the field a PATCH echoes back
// cannot disagree with the one the session was read with. Only the pde join is
// needed here; this query does no ordering, so it has no use for pda.
func (q *Queries) GetSessionSet(ctx context.Context, arg GetSessionSetParams) (GetSessionSetRow, error) {
	row := q.db.QueryRow(ctx, getSessionSet, arg.ID, arg.UserID)
	var i GetSessionSetRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ExerciseID,
		&i.ExerciseName,
		&i.SetNumber,
		&i.TargetReps,
		&i.ActualReps,
		&i.WeightLb,
		&i.Completed,
		&i.IsAssistance,
		&i.RestSeconds,
	)
	return i, err
}

const lastWeighIn = `-- name: LastWeighIn :one
SELECT s.performed_on,
       s.bodyweight_lb
FROM sessions s
WHERE s.user_id = $1::int
  AND s.id <> $2
  AND s.bodyweight_lb IS NOT NULL
ORDER BY s.performed_on DESC, s.id DESC
LIMIT 1
`

type LastWeighInParams struct {
	UserID           int32 `json:"user_id"`
	ExcludeSessionID int32 `json:"exclude_session_id"`
}

type LastWeighInRow struct {
	PerformedOn  pgtype.Date    `json:"performed_on"`
	BodyweightLb pgtype.Numeric `json:"bodyweight_lb"`
}

// LastWeighIn returns the lifter's most recent recorded bodyweight, which the
// session screen pre-fills its box with so a new session needs a nudge rather
// than a fresh entry.
//
// Deliberately excludes the session being read. A session's own weigh-in is
// already on it (GetSession above); what this answers is "what did you last
// weigh BEFORE this one", and a session that carried itself would report a
// number the lifter had already entered as something waiting to be entered.
//
// "Most recent" is by performed_on, not by created_at, so a back-dated session
// lands where the lifter says it happened. Note that this is the latest weigh-in
// overall rather than the latest one before this session's date: a session
// back-dated into the middle of a history pre-fills with today's weight, not the
// weight of the week it is filed under. That is the right default for the only
// caller — the box is a scale reading taken now — and the wrong one for a chart,
// which should read the column directly rather than through this query.
//
// :one, so no prior weigh-in is pgx.ErrNoRows and not an empty row. The caller
// has to translate that into "none" rather than let it escape as a 404.
func (q *Queries) LastWeighIn(ctx context.Context, arg LastWeighInParams) (LastWeighInRow, error) {
	row := q.db.QueryRow(ctx, lastWeighIn, arg.UserID, arg.ExcludeSessionID)
	var i LastWeighInRow
	err := row.Scan(&i.PerformedOn, &i.BodyweightLb)
	return i, err
}

const listSessionExerciseWeights = `-- name: ListSessionExerciseWeights :many
SELECT ss.session_id,
       e.name                      AS exercise_name,
       COUNT(ss.id)                AS set_count,
       MAX(ss.target_reps)::int    AS reps,
       MAX(ss.weight_lb)::numeric  AS weight_lb
FROM session_sets ss
JOIN exercises e ON e.id = ss.exercise_id
JOIN sessions s ON s.id = ss.session_id
LEFT JOIN program_day_exercises pde
  ON pde.program_day_id = s.program_day_id AND pde.exercise_id = ss.exercise_id
LEFT JOIN program_day_assistance pda
  ON pda.program_day_id = s.program_day_id
 AND pda.exercise_id = ss.exercise_id
 AND pda.user_id = s.user_id
WHERE ss.session_id = ANY($1::int[])
  AND s.user_id = $2::int
GROUP BY ss.session_id, e.name
ORDER BY ss.session_id, MIN(COALESCE(pde.position, 1000 + pda.position, 2000))
`

type ListSessionExerciseWeightsParams struct {
	SessionIds []int32 `json:"session_ids"`
	UserID     int32   `json:"user_id"`
}

type ListSessionExerciseWeightsRow struct {
	SessionID    int32          `json:"session_id"`
	ExerciseName string         `json:"exercise_name"`
	SetCount     int64          `json:"set_count"`
	Reps         int32          `json:"reps"`
	WeightLb     pgtype.Numeric `json:"weight_lb"`
}

// ListSessionExerciseWeights returns each exercise's top working weight for the
// given sessions, ordered by the day's exercise position — used to show a
// per-lift weight line on each history row.
//
// Same LEFT JOINs and same ordering expression as ListSessionSets above, for the
// same reason: an INNER JOIN here would quietly drop assistance work from the
// history list while the session detail still showed it. Keep the two in sync.
func (q *Queries) ListSessionExerciseWeights(ctx context.Context, arg ListSessionExerciseWeightsParams) ([]ListSessionExerciseWeightsRow, error) {
	rows, err := q.db.Query(ctx, listSessionExerciseWeights, arg.SessionIds, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionExerciseWeightsRow
	for rows.Next() {
		var i ListSessionExerciseWeightsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.ExerciseName,
			&i.SetCount,
			&i.Reps,
			&i.WeightLb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionPersonalBests = `-- name: ListSessionPersonalBests :many
SELECT ss.exercise_id,
       MAX(ss.weight_lb)::numeric AS best_weight_lb
FROM session_sets ss
JOIN sessions s ON s.id = ss.session_id
WHERE s.user_id = $1::int
  AND ss.session_id <> $2
  AND ss.actual_reps > 0
  AND ss.exercise_id IN (
      SELECT exercise_id FROM session_sets WHERE session_id = $2
  )
GROUP BY ss.exercise_id
`

type ListSessionPersonalBestsParams struct {
	UserID    int32 `json:"user_id"`
	SessionID int32 `json:"session_id"`
}

type ListSessionPersonalBestsRow struct {
	ExerciseID   int32          `json:"exercise_id"`
	BestWeightLb pgtype.Numeric `json:"best_weight_lb"`
}

// ListSessionPersonalBests returns, for each lift in the given session, the
// heaviest weight that lifter has ever worked on it in ANY OTHER session.
//
// This is what the active-session screen compares a logged set against to
// decide it is a personal record. It used to be one history request per
// distinct lift in the session — five or six round trips, each returning a
// whole training history, to end up with one number apiece.
//
// The current session is excluded rather than filtered client-side, which is
// what makes the answer stable: the browser previously took the maximum over
// everything it could see, so a set already logged in THIS session counted
// towards the record it was being compared against, and what qualified as a PR
// depended on when the page happened to be opened.
//
// actual_reps > 0 is the same definition of real work as ListExerciseHistory,
// so a weight only defends a record once it has actually been performed.
func (q *Queries) ListSessionPersonalBests(ctx context.Context, arg ListSessionPersonalBestsParams) ([]ListSessionPersonalBestsRow, error) {
	rows, err := q.db.Query(ctx, listSessionPersonalBests, arg.UserID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionPersonalBestsRow
	for rows.Next() {
		var i ListSessionPersonalBestsRow
		if err := rows.Scan(&i.ExerciseID, &i.BestWeightLb); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionSets = `-- name: ListSessionSets :many
SELECT ss.id,
       ss.session_id,
       ss.exercise_id,
       e.name AS exercise_name,
       ss.set_number,
       ss.target_reps,
       ss.actual_reps,
       ss.weight_lb,
       ss.completed,
       (pde.id IS NULL)::bool AS is_assistance,
       e.rest_seconds
FROM session_sets ss
JOIN exercises e ON e.id = ss.exercise_id
JOIN sessions s ON s.id = ss.session_id
LEFT JOIN program_day_exercises pde
  ON pde.program_day_id = s.program_day_id AND pde.exercise_id = ss.exercise_id
LEFT JOIN program_day_assistance pda
  ON pda.program_day_id = s.program_day_id
 AND pda.exercise_id = ss.exercise_id
 AND pda.user_id = s.user_id
WHERE ss.session_id = $1
  AND s.user_id = $2::int
ORDER BY COALESCE(pde.position, 1000 + pda.position, 2000), ss.exercise_id, ss.set_number
`

type ListSessionSetsParams struct {
	SessionID int32 `json:"session_id"`
	UserID    int32 `json:"user_id"`
}

type ListSessionSetsRow struct {
	ID           int32          `json:"id"`
	SessionID    int32          `json:"session_id"`
	ExerciseID   int32          `json:"exercise_id"`
	ExerciseName string         `json:"exercise_name"`
	SetNumber    int32          `json:"set_number"`
	TargetReps   int32          `json:"target_reps"`
	ActualReps   *int32         `json:"actual_reps"`
	WeightLb     pgtype.Numeric `json:"weight_lb"`
	Completed    bool           `json:"completed"`
	IsAssistance bool           `json:"is_assistance"`
	RestSeconds  int32          `json:"rest_seconds"`
}

// ListSessionSets returns a session's logged sets in prescription order (the
// day's main lifts by position, then that lifter's assistance, then set number),
// joined to exercise names.
//
// Both position joins are LEFT, and that is load-bearing rather than defensive.
// A set exists because it was materialized into the session; the joins here only
// decide what order to read it in. An INNER JOIN makes ordering a filter, so any
// set without a current row on the other side disappears from a finished session
// — from a record that is supposed to be immutable. Three ways that happens:
// assistance work, which has no program_day_exercises row at all; assistance the
// lifter removed after performing it; and, before assistance existed, a
// prescription edited out from under old sessions.
//
//	COALESCE(pde.position, 1000 + pda.position, 2000)
//
// reads as: main lifts in prescribed order, then assistance below them, then
// anything orphaned last. The 1000 offset is a separator, not a limit on how
// many exercises a day may hold — positions are small integers assigned max+1,
// and a day would need a thousand prescribed lifts to collide.
//
// is_assistance is derived from the same join rather than stored on the set: the
// session materializes whatever prescribe() returned, and asking "was this on
// the program's own list?" at read time cannot drift from the answer the
// ordering above already depends on.
func (q *Queries) ListSessionSets(ctx context.Context, arg ListSessionSetsParams) ([]ListSessionSetsRow, error) {
	rows, err := q.db.Query(ctx, listSessionSets, arg.SessionID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionSetsRow
	for rows.Next() {
		var i ListSessionSetsRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.SetNumber,
			&i.TargetReps,
			&i.ActualReps,
			&i.WeightLb,
			&i.Completed,
			&i.IsAssistance,
			&i.RestSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT s.id,
       s.program_day_id,
       pd.name AS program_day_name,
       p.id    AS program_id,
       p.name  AS program_name,
       s.performed_on,
       COUNT(ss.id)                              AS set_count,
       COUNT(ss.id) FILTER (WHERE ss.completed)  AS completed_set_count,
       COALESCE(SUM(ss.actual_reps * ss.weight_lb), 0)::numeric AS volume_lb,
       (s.finished_at IS NOT NULL
        OR s.created_at < now() - INTERVAL '12 hours')::bool AS is_over
FROM sessions s
JOIN program_days pd ON pd.id = s.program_day_id
JOIN programs p ON p.id = pd.program_id
LEFT JOIN session_sets ss ON ss.session_id = s.id
WHERE s.user_id = $1::int
  AND ($2::bigint IS NULL OR p.id = $2)
GROUP BY s.id, pd.name, p.id, p.name
HAVING COUNT(ss.id) FILTER (WHERE ss.actual_reps > 0) > 0
ORDER BY s.performed_on DESC, s.id DESC
LIMIT $4 OFFSET $3
`

type ListSessionsParams struct {
	UserID    int32  `json:"user_id"`
	ProgramID *int64 `json:"program_id"`
	Off       int32  `json:"off"`
	Lim       int32  `json:"lim"`
}

type ListSessionsRow struct {
	ID                int32          `json:"id"`
	ProgramDayID      int32          `json:"program_day_id"`
	ProgramDayName    string         `json:"program_day_name"`
	ProgramID         int32          `json:"program_id"`
	ProgramName       string         `json:"program_name"`
	PerformedOn       pgtype.Date    `json:"performed_on"`
	SetCount          int64          `json:"set_count"`
	CompletedSetCount int64          `json:"completed_set_count"`
	VolumeLb          pgtype.Numeric `json:"volume_lb"`
	IsOver            bool           `json:"is_over"`
}

// ListSessions returns paginated session summaries, most recent first,
// optionally filtered to one program. Pass NULL program_id for all programs.
// is_over reads s.finished_at/s.created_at under a GROUP BY: legal because the
// grouping includes s.id, the primary key, which makes every other sessions
// column functionally dependent on it.
//
// volume_lb is the weight actually moved: actual_reps, not target_reps, and
// every logged set rather than only the completed ones — a set that stopped at
// 3 of 5 reps still moved the bar three times. SUM already skips the NULL
// actual_reps of an unlogged set; COALESCE covers a session where none is
// logged. The ::numeric cast is what types the column for sqlc.
// Only sessions with at least one logged rep count as "started".
func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]ListSessionsRow, error) {
	rows, err := q.db.Query(ctx, listSessions,
		arg.UserID,
		arg.ProgramID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsRow
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramDayID,
			&i.ProgramDayName,
			&i.ProgramID,
			&i.ProgramName,
			&i.PerformedOn,
			&i.SetCount,
			&i.CompletedSetCount,
			&i.VolumeLb,
			&i.IsOver,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionTotals = `-- name: SessionTotals :one
SELECT COUNT(DISTINCT s.id)                                     AS total,
       COALESCE(SUM(ss.actual_reps * ss.weight_lb), 0)::numeric AS volume_lb
FROM sessions s
JOIN program_days pd ON pd.id = s.program_day_id
LEFT JOIN session_sets ss ON ss.session_id = s.id
WHERE s.user_id = $1::int
  AND ($2::bigint IS NULL OR pd.program_id = $2)
  AND EXISTS (
    SELECT 1 FROM session_sets ls
    WHERE ls.session_id = s.id AND ls.actual_reps > 0
  )
`

type SessionTotalsParams struct {
	UserID    int32  `json:"user_id"`
	ProgramID *int64 `json:"program_id"`
}

type SessionTotalsRow struct {
	Total    int64          `json:"total"`
	VolumeLb pgtype.Numeric `json:"volume_lb"`
}

// SessionTotals returns the two figures that describe a whole history rather
// than one page of it: how many sessions match the filter, and how much weight
// they moved between them. They are one query and not two because they must
// share a WHERE clause exactly — a second query is a second place for that
// filter to drift, and a total that counts sessions the list never returns is
// worse than no total. Hence also the EXISTS guard, which is the same "at least
// one logged rep" definition of a started session as ListSessions' HAVING.
//
// The LEFT JOIN fans one row out per set, so the count must be DISTINCT; the
// sum wants exactly that fan-out. volume_lb counts logged reps whether or not
// the set was completed, matching ListSessions above.
func (q *Queries) SessionTotals(ctx context.Context, arg SessionTotalsParams) (SessionTotalsRow, error) {
	row := q.db.QueryRow(ctx, sessionTotals, arg.UserID, arg.ProgramID)
	var i SessionTotalsRow
	err := row.Scan(&i.Total, &i.VolumeLb)
	return i, err
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET performed_on  = COALESCE($1, performed_on),
    notes         = COALESCE($2, notes),
    bodyweight_lb = CASE WHEN $3::bool
                         THEN $4::numeric
                         ELSE bodyweight_lb END
WHERE id = $5
  AND user_id = $6::int
RETURNING id, program_day_id, performed_on, notes, created_at, finished_at, user_id, bodyweight_lb
`

type UpdateSessionParams struct {
	PerformedOn   pgtype.Date    `json:"performed_on"`
	Notes         *string        `json:"notes"`
	SetBodyweight bool           `json:"set_bodyweight"`
	BodyweightLb  pgtype.Numeric `json:"bodyweight_lb"`
	ID            int32          `json:"id"`
	UserID        int32          `json:"user_id"`
}

// UpdateSession patches metadata; NULL args leave a column unchanged.
//
// bodyweight_lb cannot use that convention, because clearing a weigh-in and
// leaving it alone are different requests and COALESCE renders them identically
// — the same problem, and the same reasoning, as actual_reps in UpdateSessionSet
// below. set_bodyweight is what separates them: false means the PATCH body had
// no bodyweightLb key at all, true means it had one, and the value may then be
// NULL to erase the entry. The ::numeric cast types the branch for sqlc, which
// has no column to infer from inside a CASE.
func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSession,
		arg.PerformedOn,
		arg.Notes,
		arg.SetBodyweight,
		arg.BodyweightLb,
		arg.ID,
		arg.UserID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProgramDayID,
		&i.PerformedOn,
		&i.Notes,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.UserID,
		&i.BodyweightLb,
	)
	return i, err
}

const updateSessionSet = `-- name: UpdateSessionSet :one
UPDATE session_sets ss
SET actual_reps = $1,
    weight_lb   = $2,
    completed   = $3
FROM sessions s
WHERE ss.id = $4
  AND s.id = ss.session_id
  AND s.user_id = $5::int
RETURNING ss.id, ss.session_id, ss.exercise_id, ss.set_number, ss.target_reps, ss.actual_reps, ss.weight_lb, ss.completed
`

type UpdateSessionSetParams struct {
	ActualReps *int32         `json:"actual_reps"`
	WeightLb   pgtype.Numeric `json:"weight_lb"`
	Completed  bool           `json:"completed"`
	ID         int32          `json:"id"`
	UserID     int32          `json:"user_id"`
}

// UpdateSessionSet writes all three mutable columns; the handler merges the
// PATCH body with current values first, so actual_reps can be set to NULL to
// clear a prior entry (COALESCE could not express that). The owner check is
// repeated here rather than inferred from the preceding GetSessionSet: an
// UPDATE that trusts a prior read is one refactor away from trusting nothing.
func (q *Queries) UpdateSessionSet(ctx context.Context, arg UpdateSessionSetParams) (SessionSet, error) {
	row := q.db.QueryRow(ctx, updateSessionSet,
		arg.ActualReps,
		arg.WeightLb,
		arg.Completed,
		arg.ID,
		arg.UserID,
	)
	var i SessionSet
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ExerciseID,
		&i.SetNumber,
		&i.TargetReps,
		&i.ActualReps,
		&i.WeightLb,
		&i.Completed,
	)
	return i, err
}
