// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adoptOrphanSessions = `-- name: AdoptOrphanSessions :execrows
UPDATE sessions
SET user_id = $1::int
WHERE user_id IS NULL
`

// AdoptOrphanSessions hands every unowned session to a user. Run once, inside
// the transaction that creates the first account: sessions logged before this
// feature existed have user_id IS NULL and are invisible to every scoped query,
// so without this the install's entire history would silently disappear.
func (q *Queries) AdoptOrphanSessions(ctx context.Context, userID int32) (int64, error) {
	result, err := q.db.Exec(ctx, adoptOrphanSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countUsers = `-- name: CountUsers :one

SELECT COUNT(*) AS total FROM users
`

// Accounts, login sessions, and avatars.
//
// password_hash is selected by exactly one query (GetUserForLogin). Every other
// query lists columns explicitly and omits it, so a hash cannot reach a DTO by
// accident — the compiler stops it, because the row struct has no such field.
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, display_name, password_hash, is_admin, must_change_password)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, display_name, avatar_color, is_admin, created_at, updated_at, current_program_id, must_change_password
`

type CreateUserParams struct {
	Username           string `json:"username"`
	DisplayName        string `json:"display_name"`
	PasswordHash       string `json:"password_hash"`
	IsAdmin            bool   `json:"is_admin"`
	MustChangePassword bool   `json:"must_change_password"`
}

type CreateUserRow struct {
	ID                 int32              `json:"id"`
	Username           string             `json:"username"`
	DisplayName        string             `json:"display_name"`
	AvatarColor        string             `json:"avatar_color"`
	IsAdmin            bool               `json:"is_admin"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CurrentProgramID   *int32             `json:"current_program_id"`
	MustChangePassword bool               `json:"must_change_password"`
}

// CreateUser makes an account. Both flags are explicit parameters rather than
// defaults, because the two callers differ on both: registration creates the
// install's single admin with a password its owner chose, and the admin area
// creates an ordinary account with a password somebody else chose — which is
// exactly the case must_change_password exists for.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.IsAdmin,
		arg.MustChangePassword,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarColor,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentProgramID,
		&i.MustChangePassword,
	)
	return i, err
}

const createUserSession = `-- name: CreateUserSession :exec

INSERT INTO user_sessions (token_hash, user_id, expires_at, persistent)
VALUES ($1, $2::int, $3, $4)
`

type CreateUserSessionParams struct {
	TokenHash  []byte             `json:"token_hash"`
	UserID     int32              `json:"user_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	Persistent bool               `json:"persistent"`
}

// ---- login sessions ----
func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) error {
	_, err := q.db.Exec(ctx, createUserSession,
		arg.TokenHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.Persistent,
	)
	return err
}

const deleteExpiredUserSessions = `-- name: DeleteExpiredUserSessions :execrows
DELETE FROM user_sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredUserSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredUserSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserAvatar = `-- name: DeleteUserAvatar :execrows
DELETE FROM user_avatars WHERE user_id = $1::int
`

func (q *Queries) DeleteUserAvatar(ctx context.Context, userID int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserAvatar, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserSession = `-- name: DeleteUserSession :exec
DELETE FROM user_sessions WHERE token_hash = $1
`

func (q *Queries) DeleteUserSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteUserSession, tokenHash)
	return err
}

const deleteUserSessionsExcept = `-- name: DeleteUserSessionsExcept :execrows
DELETE FROM user_sessions
WHERE user_id = $1::int
  AND token_hash <> $2
`

type DeleteUserSessionsExceptParams struct {
	UserID    int32  `json:"user_id"`
	TokenHash []byte `json:"token_hash"`
}

// DeleteUserSessionsExcept revokes every other login for a user, used on
// password change: the point of changing a password is to lock out whoever
// might have had the old one, which is not achieved if their cookie survives.
func (q *Queries) DeleteUserSessionsExcept(ctx context.Context, arg DeleteUserSessionsExceptParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserSessionsExcept, arg.UserID, arg.TokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLifter = `-- name: GetLifter :one
SELECT u.id,
       u.username,
       u.display_name,
       u.avatar_color,
       COALESCE(ua.etag, '') AS avatar_etag,
       u.current_program_id,
       (
         SELECT MAX(s.performed_on)
         FROM sessions s
         WHERE s.user_id = u.id
           AND EXISTS (
             SELECT 1 FROM session_sets ss
             WHERE ss.session_id = s.id AND ss.actual_reps > 0
           )
       )::date AS last_trained_on
FROM users u
LEFT JOIN user_avatars ua ON ua.user_id = u.id
WHERE u.id = $1
`

type GetLifterRow struct {
	ID               int32       `json:"id"`
	Username         string      `json:"username"`
	DisplayName      string      `json:"display_name"`
	AvatarColor      string      `json:"avatar_color"`
	AvatarEtag       string      `json:"avatar_etag"`
	CurrentProgramID *int32      `json:"current_program_id"`
	LastTrainedOn    pgtype.Date `json:"last_trained_on"`
}

// GetLifter is one row of the roster above, for the profile page.
//
// Same column list and the same reasoning about what is left out, so the two
// cannot disagree about what one lifter may know about another — if a column is
// ever added to one of these, it belongs in both or in neither.
//
// Not GetUser, which returns the administrative columns. Reusing it and simply
// declining to copy those into the DTO would work today and is the arrangement
// that rots: the fields would be sitting in a struct in a social handler, one
// careless assignment away from being sent. The compiler enforcing their absence
// is worth a near-duplicate query, which is the same trade the note at the top
// of this file makes for password_hash.
//
// current_program_id rides along because the profile names what this lifter is
// currently running. It is a program id, not a prescription — shared data that
// every account can already read through /programs.
func (q *Queries) GetLifter(ctx context.Context, id int32) (GetLifterRow, error) {
	row := q.db.QueryRow(ctx, getLifter, id)
	var i GetLifterRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarColor,
		&i.AvatarEtag,
		&i.CurrentProgramID,
		&i.LastTrainedOn,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, display_name, avatar_color, is_admin, created_at, updated_at, current_program_id, must_change_password
FROM users
WHERE id = $1
`

type GetUserRow struct {
	ID                 int32              `json:"id"`
	Username           string             `json:"username"`
	DisplayName        string             `json:"display_name"`
	AvatarColor        string             `json:"avatar_color"`
	IsAdmin            bool               `json:"is_admin"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CurrentProgramID   *int32             `json:"current_program_id"`
	MustChangePassword bool               `json:"must_change_password"`
}

func (q *Queries) GetUser(ctx context.Context, id int32) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarColor,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentProgramID,
		&i.MustChangePassword,
	)
	return i, err
}

const getUserAvatar = `-- name: GetUserAvatar :one
SELECT user_id, mime, bytes, etag, updated_at
FROM user_avatars
WHERE user_id = $1::int
`

func (q *Queries) GetUserAvatar(ctx context.Context, userID int32) (UserAvatar, error) {
	row := q.db.QueryRow(ctx, getUserAvatar, userID)
	var i UserAvatar
	err := row.Scan(
		&i.UserID,
		&i.Mime,
		&i.Bytes,
		&i.Etag,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAvatarEtag = `-- name: GetUserAvatarEtag :one
SELECT etag FROM user_avatars WHERE user_id = $1::int
`

// GetUserAvatarEtag reads just the tag, so rendering a profile does not pull
// the image bytes through the connection to decide whether one exists.
func (q *Queries) GetUserAvatarEtag(ctx context.Context, userID int32) (string, error) {
	row := q.db.QueryRow(ctx, getUserAvatarEtag, userID)
	var etag string
	err := row.Scan(&etag)
	return etag, err
}

const getUserForLogin = `-- name: GetUserForLogin :one
SELECT id, username, display_name, avatar_color, password_hash, is_admin, created_at, updated_at, current_program_id, must_change_password
FROM users
WHERE lower(username) = lower($1)
`

// GetUserForLogin is the only query that reads password_hash. Username is
// matched case-insensitively, which is why users_username_lower_idx exists.
//
// The column list is in table order, which is what makes sqlc return the User
// model here rather than a bespoke row struct. Keep new columns at the end.
func (q *Queries) GetUserForLogin(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserForLogin, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarColor,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentProgramID,
		&i.MustChangePassword,
	)
	return i, err
}

const getUserSession = `-- name: GetUserSession :one
SELECT s.token_hash,
       s.user_id,
       s.created_at,
       s.last_seen,
       s.expires_at,
       s.persistent,
       u.username,
       u.display_name,
       u.avatar_color,
       u.is_admin,
       u.current_program_id,
       -- Joined here rather than read by a second query: the forced-change gate
       -- runs on every authenticated request, and authenticating one is meant
       -- to be a single round trip.
       u.must_change_password
FROM user_sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.expires_at > now()
`

type GetUserSessionRow struct {
	TokenHash          []byte             `json:"token_hash"`
	UserID             int32              `json:"user_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	LastSeen           pgtype.Timestamptz `json:"last_seen"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	Persistent         bool               `json:"persistent"`
	Username           string             `json:"username"`
	DisplayName        string             `json:"display_name"`
	AvatarColor        string             `json:"avatar_color"`
	IsAdmin            bool               `json:"is_admin"`
	CurrentProgramID   *int32             `json:"current_program_id"`
	MustChangePassword bool               `json:"must_change_password"`
}

// GetUserSession resolves a presented cookie to its owner, joined so that
// authenticating a request is a single round trip. Expired rows are filtered
// here rather than in Go: the check then cannot be forgotten by a caller, and
// a clock skew between app and database can't extend a session.
func (q *Queries) GetUserSession(ctx context.Context, tokenHash []byte) (GetUserSessionRow, error) {
	row := q.db.QueryRow(ctx, getUserSession, tokenHash)
	var i GetUserSessionRow
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeen,
		&i.ExpiresAt,
		&i.Persistent,
		&i.Username,
		&i.DisplayName,
		&i.AvatarColor,
		&i.IsAdmin,
		&i.CurrentProgramID,
		&i.MustChangePassword,
	)
	return i, err
}

const listLifters = `-- name: ListLifters :many
SELECT u.id,
       u.username,
       u.display_name,
       u.avatar_color,
       COALESCE(ua.etag, '') AS avatar_etag,
       (
         SELECT MAX(s.performed_on)
         FROM sessions s
         WHERE s.user_id = u.id
           AND EXISTS (
             SELECT 1 FROM session_sets ss
             WHERE ss.session_id = s.id AND ss.actual_reps > 0
           )
       )::date AS last_trained_on
FROM users u
LEFT JOIN user_avatars ua ON ua.user_id = u.id
ORDER BY u.created_at, u.id
`

type ListLiftersRow struct {
	ID            int32       `json:"id"`
	Username      string      `json:"username"`
	DisplayName   string      `json:"display_name"`
	AvatarColor   string      `json:"avatar_color"`
	AvatarEtag    string      `json:"avatar_etag"`
	LastTrainedOn pgtype.Date `json:"last_trained_on"`
}

// ListLifters is the social roster: every account on this install, as one
// lifter sees another.
//
// Deliberately not ListUsers, though the FROM clause is identical. That one
// answers an administrative question and carries two administrative columns:
// is_admin, and must_change_password. Neither belongs in an answer given to an
// ordinary account. must_change_password is the sharper of the two — it means
// "the one-time password this account was created with is still live, and still
// known to whoever typed it", which is a fact about a credential and is the
// owner's business alone. Sending it to every lifter on the install would leak
// which accounts have not yet been picked up.
//
// is_admin is milder but goes the same way: who administers the install is not
// part of how lifters see each other, and a roster that marked one row as the
// owner would be answering a question nobody on this screen asked.
//
// last_trained_on is the one column this has and ListUsers does not, and it is
// what makes the roster read as people rather than rows. It is a correlated
// subquery rather than a LEFT JOIN with a GROUP BY because the join would fan
// one user out per session and the grouping would have to put it back; at a
// handful of accounts the planner runs this once per row and the cost is
// nothing.
//
// The EXISTS guard is the same "at least one logged rep" definition of a
// started session that ListSessions' HAVING and SessionTotals' own EXISTS use.
// Keeping the three in agreement is the point: a session somebody opened and
// walked away from without logging anything is not a day they trained, and a
// roster that dated it as one would be the app disagreeing with its own history
// page about the same row.
//
// NULL means this account has never logged a rep, which the API sends as an
// absent field and the UI reads as "has not trained yet" — not as a date it
// has to invent.
//
// Ordered like ListUsers, and for the same reason: oldest account first, so the
// list is stable. Sorting by last_trained_on would be the more obviously social
// choice and is the wrong one here — it makes a roster of five people reorder
// itself every time somebody trains, so the row a lifter reaches for moves
// between visits to buy an ordering nobody needed at this size.
//
// avatar_etag is joined rather than looked up per row. The avatar bytes are not
// read — only the tag, which is what the UI needs to decide between an <img> and
// an initials chip and to bust its cache, exactly as GetUserAvatarEtag serves
// /me. Joining it is what keeps a roster one query instead of one per lifter;
// LEFT, because most accounts never upload anything, and COALESCE so "no
// avatar" arrives as an empty string rather than a NULL every caller would have
// to branch on.
func (q *Queries) ListLifters(ctx context.Context) ([]ListLiftersRow, error) {
	rows, err := q.db.Query(ctx, listLifters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiftersRow
	for rows.Next() {
		var i ListLiftersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarColor,
			&i.AvatarEtag,
			&i.LastTrainedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, display_name, avatar_color, is_admin, created_at, must_change_password
FROM users
ORDER BY created_at, id
`

type ListUsersRow struct {
	ID                 int32              `json:"id"`
	Username           string             `json:"username"`
	DisplayName        string             `json:"display_name"`
	AvatarColor        string             `json:"avatar_color"`
	IsAdmin            bool               `json:"is_admin"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	MustChangePassword bool               `json:"must_change_password"`
}

// ListUsers is the admin roster. No password_hash, per the note at the top of
// this file — and no gym, which the admin screen has no use for and which would
// cost three more queries per row.
//
// Oldest first, so the owner (the account that claimed the install) heads the
// list and later additions append in the order they were made. id breaks ties
// for rows created in the same tick.
func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarColor,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.MustChangePassword,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRegistration = `-- name: LockRegistration :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

// LockRegistration serializes the first-user check against concurrent
// registrations. It must be taken *before* CountUsers, inside the same
// transaction: the check asks whether any row exists, and a COUNT over rows
// that do not exist yet takes no lock that a second transaction would block on.
// Two racing registrations with different usernames would otherwise both see an
// empty table and both commit.
//
// pg_advisory_xact_lock releases at commit or rollback, so a crashed request
// cannot wedge registration. The key is arbitrary but fixed — see
// registrationLockKey in the api package.
func (q *Queries) LockRegistration(ctx context.Context, key int64) error {
	_, err := q.db.Exec(ctx, lockRegistration, key)
	return err
}

const rehashUserPassword = `-- name: RehashUserPassword :execrows
UPDATE users
SET password_hash = $1,
    updated_at    = now()
WHERE id = $2
`

type RehashUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int32  `json:"id"`
}

// RehashUserPassword upgrades a stored hash to current parameters, leaving
// must_change_password alone.
//
// Separate from UpdateUserPassword because it runs at a different moment for a
// different reason: login calls it after verifying the password the account
// already has. Sharing the query above would mean a lifter clearing the forced
// change simply by signing in with the one-time password the admin gave them —
// the flag would be cleared by USING that credential rather than by replacing
// it, which is the one thing it exists to prevent.
func (q *Queries) RehashUserPassword(ctx context.Context, arg RehashUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, rehashUserPassword, arg.PasswordHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchUserSession = `-- name: TouchUserSession :exec
UPDATE user_sessions
SET last_seen  = now(),
    expires_at = now() + make_interval(secs => $1::int)
WHERE token_hash = $2
`

type TouchUserSessionParams struct {
	TtlSeconds int32  `json:"ttl_seconds"`
	TokenHash  []byte `json:"token_hash"`
}

// TouchUserSession slides a persistent session forward so an active user is
// never signed out by the clock. Called only when last_seen is already stale,
// so a busy client does not write a row per request.
// Expiry is computed from the database's now(), not the application's clock, so
// a skewed app pod cannot hand out sessions that outlive their intended window.
// make_interval takes a plain integer, which keeps the parameter an int rather
// than an interval type the driver would have to encode.
func (q *Queries) TouchUserSession(ctx context.Context, arg TouchUserSessionParams) error {
	_, err := q.db.Exec(ctx, touchUserSession, arg.TtlSeconds, arg.TokenHash)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users
SET password_hash        = $1,
    must_change_password = false,
    updated_at           = now()
WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int32  `json:"id"`
}

// UpdateUserPassword is the user-initiated change, and it clears
// must_change_password: an account created by the admin area reaches nothing but
// /me and this endpoint until the flag goes, so this is the only way out of the
// gate. Deliberately NOT the query the login re-hash uses — see
// RehashUserPassword.
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name       = COALESCE($1, display_name),
    avatar_color       = COALESCE($2, avatar_color),
    current_program_id = COALESCE($3, current_program_id),
    updated_at         = now()
WHERE id = $4
RETURNING id, username, display_name, avatar_color, is_admin, created_at, updated_at, current_program_id, must_change_password
`

type UpdateUserProfileParams struct {
	DisplayName      *string `json:"display_name"`
	AvatarColor      *string `json:"avatar_color"`
	CurrentProgramID *int32  `json:"current_program_id"`
	ID               int32   `json:"id"`
}

type UpdateUserProfileRow struct {
	ID                 int32              `json:"id"`
	Username           string             `json:"username"`
	DisplayName        string             `json:"display_name"`
	AvatarColor        string             `json:"avatar_color"`
	IsAdmin            bool               `json:"is_admin"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CurrentProgramID   *int32             `json:"current_program_id"`
	MustChangePassword bool               `json:"must_change_password"`
}

// UpdateUserProfile patches the display fields; NULL args leave a column
// unchanged. avatar_color is COALESCEd like the rest, so clearing it back to
// the derived default is done by sending an empty string, not null.
//
// current_program_id is patched the same way, which means the API can set it
// but not clear it. Nothing needs to: the column goes back to NULL when the
// program it names is deleted, and that is the only way it should empty.
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.DisplayName,
		arg.AvatarColor,
		arg.CurrentProgramID,
		arg.ID,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarColor,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentProgramID,
		&i.MustChangePassword,
	)
	return i, err
}

const upsertUserAvatar = `-- name: UpsertUserAvatar :exec

INSERT INTO user_avatars (user_id, mime, bytes, etag, updated_at)
VALUES ($1::int, $2, $3, $4, now())
ON CONFLICT (user_id) DO UPDATE
SET mime = EXCLUDED.mime,
    bytes = EXCLUDED.bytes,
    etag = EXCLUDED.etag,
    updated_at = now()
`

type UpsertUserAvatarParams struct {
	UserID int32  `json:"user_id"`
	Mime   string `json:"mime"`
	Bytes  []byte `json:"bytes"`
	Etag   string `json:"etag"`
}

// ---- avatars ----
func (q *Queries) UpsertUserAvatar(ctx context.Context, arg UpsertUserAvatarParams) error {
	_, err := q.db.Exec(ctx, upsertUserAvatar,
		arg.UserID,
		arg.Mime,
		arg.Bytes,
		arg.Etag,
	)
	return err
}
