// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adoptOrphanSessions = `-- name: AdoptOrphanSessions :execrows
UPDATE sessions
SET user_id = $1::int
WHERE user_id IS NULL
`

// AdoptOrphanSessions hands every unowned session to a user. Run once, inside
// the transaction that creates the first account: sessions logged before this
// feature existed have user_id IS NULL and are invisible to every scoped query,
// so without this the install's entire history would silently disappear.
func (q *Queries) AdoptOrphanSessions(ctx context.Context, userID int32) (int64, error) {
	result, err := q.db.Exec(ctx, adoptOrphanSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) AS total FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, display_name, password_hash, is_admin)
VALUES ($1, $2, $3, $4)
RETURNING id, username, display_name, avatar_color, is_admin, created_at, updated_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	DisplayName  string `json:"display_name"`
	PasswordHash string `json:"password_hash"`
	IsAdmin      bool   `json:"is_admin"`
}

type CreateUserRow struct {
	ID          int32              `json:"id"`
	Username    string             `json:"username"`
	DisplayName string             `json:"display_name"`
	AvatarColor string             `json:"avatar_color"`
	IsAdmin     bool               `json:"is_admin"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.IsAdmin,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarColor,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserSession = `-- name: CreateUserSession :exec
INSERT INTO user_sessions (token_hash, user_id, expires_at, persistent)
VALUES ($1, $2::int, $3, $4)
`

type CreateUserSessionParams struct {
	TokenHash  []byte             `json:"token_hash"`
	UserID     int32              `json:"user_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	Persistent bool               `json:"persistent"`
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) error {
	_, err := q.db.Exec(ctx, createUserSession,
		arg.TokenHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.Persistent,
	)
	return err
}

const deleteExpiredUserSessions = `-- name: DeleteExpiredUserSessions :execrows
DELETE FROM user_sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredUserSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredUserSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserAvatar = `-- name: DeleteUserAvatar :execrows
DELETE FROM user_avatars WHERE user_id = $1::int
`

func (q *Queries) DeleteUserAvatar(ctx context.Context, userID int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserAvatar, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserSession = `-- name: DeleteUserSession :exec
DELETE FROM user_sessions WHERE token_hash = $1
`

func (q *Queries) DeleteUserSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteUserSession, tokenHash)
	return err
}

const deleteUserSessionsExcept = `-- name: DeleteUserSessionsExcept :execrows
DELETE FROM user_sessions
WHERE user_id = $1::int
  AND token_hash <> $2
`

type DeleteUserSessionsExceptParams struct {
	UserID    int32  `json:"user_id"`
	TokenHash []byte `json:"token_hash"`
}

// DeleteUserSessionsExcept revokes every other login for a user, used on
// password change: the point of changing a password is to lock out whoever
// might have had the old one, which is not achieved if their cookie survives.
func (q *Queries) DeleteUserSessionsExcept(ctx context.Context, arg DeleteUserSessionsExceptParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserSessionsExcept, arg.UserID, arg.TokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUser = `-- name: GetUser :one
SELECT id, username, display_name, avatar_color, is_admin, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserRow struct {
	ID          int32              `json:"id"`
	Username    string             `json:"username"`
	DisplayName string             `json:"display_name"`
	AvatarColor string             `json:"avatar_color"`
	IsAdmin     bool               `json:"is_admin"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUser(ctx context.Context, id int32) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarColor,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAvatar = `-- name: GetUserAvatar :one
SELECT user_id, mime, bytes, etag, updated_at
FROM user_avatars
WHERE user_id = $1::int
`

func (q *Queries) GetUserAvatar(ctx context.Context, userID int32) (UserAvatar, error) {
	row := q.db.QueryRow(ctx, getUserAvatar, userID)
	var i UserAvatar
	err := row.Scan(
		&i.UserID,
		&i.Mime,
		&i.Bytes,
		&i.Etag,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAvatarEtag = `-- name: GetUserAvatarEtag :one
SELECT etag FROM user_avatars WHERE user_id = $1::int
`

// GetUserAvatarEtag reads just the tag, so rendering a profile does not pull
// the image bytes through the connection to decide whether one exists.
func (q *Queries) GetUserAvatarEtag(ctx context.Context, userID int32) (string, error) {
	row := q.db.QueryRow(ctx, getUserAvatarEtag, userID)
	var etag string
	err := row.Scan(&etag)
	return etag, err
}

const getUserForLogin = `-- name: GetUserForLogin :one
SELECT id, username, display_name, avatar_color, password_hash, is_admin, created_at, updated_at
FROM users
WHERE lower(username) = lower($1)
`

// GetUserForLogin is the only query that reads password_hash. Username is
// matched case-insensitively, which is why users_username_lower_idx exists.
func (q *Queries) GetUserForLogin(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserForLogin, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarColor,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSession = `-- name: GetUserSession :one
SELECT s.token_hash,
       s.user_id,
       s.created_at,
       s.last_seen,
       s.expires_at,
       s.persistent,
       u.username,
       u.display_name,
       u.avatar_color,
       u.is_admin
FROM user_sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.expires_at > now()
`

type GetUserSessionRow struct {
	TokenHash   []byte             `json:"token_hash"`
	UserID      int32              `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastSeen    pgtype.Timestamptz `json:"last_seen"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	Persistent  bool               `json:"persistent"`
	Username    string             `json:"username"`
	DisplayName string             `json:"display_name"`
	AvatarColor string             `json:"avatar_color"`
	IsAdmin     bool               `json:"is_admin"`
}

// GetUserSession resolves a presented cookie to its owner, joined so that
// authenticating a request is a single round trip. Expired rows are filtered
// here rather than in Go: the check then cannot be forgotten by a caller, and
// a clock skew between app and database can't extend a session.
func (q *Queries) GetUserSession(ctx context.Context, tokenHash []byte) (GetUserSessionRow, error) {
	row := q.db.QueryRow(ctx, getUserSession, tokenHash)
	var i GetUserSessionRow
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeen,
		&i.ExpiresAt,
		&i.Persistent,
		&i.Username,
		&i.DisplayName,
		&i.AvatarColor,
		&i.IsAdmin,
	)
	return i, err
}

const touchUserSession = `-- name: TouchUserSession :exec
UPDATE user_sessions
SET last_seen  = now(),
    expires_at = now() + make_interval(secs => $1::int)
WHERE token_hash = $2
`

type TouchUserSessionParams struct {
	TtlSeconds int32  `json:"ttl_seconds"`
	TokenHash  []byte `json:"token_hash"`
}

// Expiry is computed from the database's now(), not the application's clock, so
// a skewed app pod cannot hand out sessions that outlive their intended window.
// make_interval takes a plain integer, which keeps the parameter an int rather
// than an interval type the driver would have to encode.
// TouchUserSession slides a persistent session forward so an active user is
// never signed out by the clock. Called only when last_seen is already stale,
// so a busy client does not write a row per request.
func (q *Queries) TouchUserSession(ctx context.Context, arg TouchUserSessionParams) error {
	_, err := q.db.Exec(ctx, touchUserSession, arg.TtlSeconds, arg.TokenHash)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users
SET password_hash = $1,
    updated_at    = now()
WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int32  `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = COALESCE($1, display_name),
    avatar_color = COALESCE($2, avatar_color),
    updated_at   = now()
WHERE id = $3
RETURNING id, username, display_name, avatar_color, is_admin, created_at, updated_at
`

type UpdateUserProfileParams struct {
	DisplayName *string `json:"display_name"`
	AvatarColor *string `json:"avatar_color"`
	ID          int32   `json:"id"`
}

type UpdateUserProfileRow struct {
	ID          int32              `json:"id"`
	Username    string             `json:"username"`
	DisplayName string             `json:"display_name"`
	AvatarColor string             `json:"avatar_color"`
	IsAdmin     bool               `json:"is_admin"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// UpdateUserProfile patches the display fields; NULL args leave a column
// unchanged. avatar_color is COALESCEd like the rest, so clearing it back to
// the derived default is done by sending an empty string, not null.
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.DisplayName, arg.AvatarColor, arg.ID)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarColor,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserAvatar = `-- name: UpsertUserAvatar :exec
INSERT INTO user_avatars (user_id, mime, bytes, etag, updated_at)
VALUES ($1::int, $2, $3, $4, now())
ON CONFLICT (user_id) DO UPDATE
SET mime = EXCLUDED.mime,
    bytes = EXCLUDED.bytes,
    etag = EXCLUDED.etag,
    updated_at = now()
`

type UpsertUserAvatarParams struct {
	UserID int32  `json:"user_id"`
	Mime   string `json:"mime"`
	Bytes  []byte `json:"bytes"`
	Etag   string `json:"etag"`
}

func (q *Queries) UpsertUserAvatar(ctx context.Context, arg UpsertUserAvatarParams) error {
	_, err := q.db.Exec(ctx, upsertUserAvatar,
		arg.UserID,
		arg.Mime,
		arg.Bytes,
		arg.Etag,
	)
	return err
}
